import { db } from "./db";
import { events, users } from "../shared/schema";

const dutchEvents = [
  {
    title: "Amsterdam Hip-Hop Festival 2026",
    description: `Het grootste hip-hop festival van Nederland keert terug naar de Westergasfabriek! Met meer dan 30 nationale en internationale artiesten, dj's, b-boys/b-girls, graffitikunstenaars en spoken word-performers. Dit is hét event voor de hele urban culture gemeenschap.\n\n🎟️ TICKETS KOPEN:\nTickets zijn verkrijgbaar via Ticketmaster.nl. Early bird tickets voor €20, reguliere tickets voor €25. VIP combipakketten inclusief backstage-toegang voor €65 via de officiële website. Tickets ook te koop bij de Westergasfabriek-kassa.`,
    date: new Date("2026-04-18T14:00:00"),
    endDate: new Date("2026-04-19T23:00:00"),
    location: "Westergasfabriek Amsterdam",
    city: "Amsterdam",
    category: "festival",
    subcategory: "hip-hop",
    isPaid: true,
    price: 25,
    priceModel: "from",
    adultPrice: 25,
    kidsPrice: 10,
    familyPrice: 60,
    image: "https://images.unsplash.com/photo-1535928148101-3c975e8c4afe?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1547347298-4074fc3086f0?w=800&q=80",
      "https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=800&q=80",
      "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80",
    ],
    tags: ["hip-hop", "festival", "live-muziek", "graffiti", "breakdance"],
    vibeLabels: ["Urban", "Energetic"],
    moodTags: ["energetic", "urban"],
    capacity: 5000,
    attendeeCount: 3200,
    likeCount: 487,
    kidFriendly: true,
    familyFriendly: true,
    isIndoor: false,
    crowdLevel: "busy",
    isFeatured: true,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.ticketmaster.nl/search?q=amsterdam+hip+hop+festival",
    organizerBio: "Amsterdam Hip-Hop Foundation organiseert al 12 jaar lang het grootste hip-hop festival van Nederland.",
  },
  {
    title: "Red Bull BC One Netherlands Qualifier",
    description: `De Nederlandse kwalificatieronde voor de meest prestigieuze breaking wedstrijd ter wereld — Red Bull BC One! De beste B-Boys en B-Girls van Nederland strijden om een plek in de World Final. Spektakel gegarandeerd.\n\n🎟️ TICKETS KOPEN:\nToegankelijk voor iedereen — GRATIS entree voor toeschouwers! Inschrijving voor deelnemers via de officiële Red Bull BC One website. Registreer je voor 1 mei via redbull.com/bcone.`,
    date: new Date("2026-05-16T13:00:00"),
    endDate: new Date("2026-05-16T22:00:00"),
    location: "AFAS Live Amsterdam",
    city: "Amsterdam",
    category: "dance",
    subcategory: "breaking",
    isPaid: false,
    price: 0,
    priceModel: "free",
    image: "https://images.unsplash.com/photo-1547347298-4074fc3086f0?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1484972759836-b93f9ef2b293?w=800&q=80",
      "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80",
    ],
    tags: ["breaking", "b-boy", "b-girl", "red-bull", "competitie"],
    vibeLabels: ["Energetic", "Urban"],
    moodTags: ["energetic", "competitive"],
    capacity: 2000,
    attendeeCount: 1800,
    likeCount: 634,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: true,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.redbull.com/nl-nl/bcone",
    organizerBio: "Red Bull organiseert wereldwijd de meest iconische breaking competities.",
  },
  {
    title: "NDSM Street Art Festival",
    description: `Het NDSM-terrein in Amsterdam Noord transformeert weer in een open lucht museum van world-class street art. Internationale en Nederlandse graffitikunstenaars, murals, live painting sessies, workshops en installaties. Een unieke beleving voor kunstliefhebbers van alle leeftijden.\n\n🎟️ TICKETS KOPEN:\nVRIJ entree — het hele terrein is toegankelijk. Wil je deelnemen aan de exclusieve Live Painting Workshop? Schrijf je in via Eventbrite voor €15 per persoon.`,
    date: new Date("2026-06-06T11:00:00"),
    endDate: new Date("2026-06-07T20:00:00"),
    location: "NDSM-werf Amsterdam",
    city: "Amsterdam",
    category: "art",
    subcategory: "graffiti",
    isPaid: false,
    price: 0,
    priceModel: "free",
    image: "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=800&q=80",
      "https://images.unsplash.com/photo-1526327760257-75f515b7a5c3?w=800&q=80",
    ],
    tags: ["street-art", "graffiti", "mural", "workshop", "live-painting"],
    vibeLabels: ["Creative", "Chill"],
    moodTags: ["creative", "chill"],
    capacity: 3000,
    attendeeCount: 2100,
    likeCount: 312,
    kidFriendly: true,
    familyFriendly: true,
    isIndoor: false,
    crowdLevel: "medium",
    isFeatured: false,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.eventbrite.nl/e/ndsm-street-art-festival-2026",
    organizerBio: "NDSM-werf is het creatieve hart van Amsterdam Noord.",
  },
  {
    title: "Groove Sessions Amsterdam — Paradiso",
    description: `Groove Sessions is de meest geliefde dansavond van Amsterdam, nu in de iconische zaal van Paradiso! Een nacht vol breaking, popping, locking, hip-hop en house battles met toppers uit de nationale scene. DJ-line-up met de beste urban beats.\n\n🎟️ TICKETS KOPEN:\nTickets uitsluitend via Paradiso.nl — €18 voor leden, €22 voor niet-leden. Online kopen aanbevolen want het event is snel uitverkocht! Kassa op de avond zelf open als er nog tickets over zijn.`,
    date: new Date("2026-03-28T21:00:00"),
    endDate: new Date("2026-03-29T04:00:00"),
    location: "Paradiso Amsterdam",
    city: "Amsterdam",
    category: "dance",
    subcategory: "hip-hop dance",
    isPaid: true,
    price: 22,
    priceModel: "paid",
    adultPrice: 22,
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1547347298-4074fc3086f0?w=800&q=80",
      "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&q=80",
    ],
    tags: ["breaking", "popping", "locking", "hip-hop", "nachtleven"],
    vibeLabels: ["Energetic", "Urban"],
    moodTags: ["energetic", "party"],
    capacity: 1200,
    attendeeCount: 980,
    likeCount: 521,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: true,
    isTrending: false,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.paradiso.nl/en/agenda/groove-sessions",
    organizerBio: "Groove Sessions brengt al 8 jaar de beste urban dansers samen in Amsterdam.",
  },
  {
    title: "Rotterdam Dance Festival — Urban Edition",
    description: `Rotterdam Dance Festival Urban brengt de kracht van stads-dans naar Rotterdam Ahoy. Met battles in breaking, waacking, voguing, dancehall en krump. Gastjurys uit de internationale scene en live muzikanten begeleiden de strijd.\n\n🎟️ TICKETS KOPEN:\nTickets via Ahoy.nl — Dagticket €15, Weekend €25. Vroegboekkorting beschikbaar tot 1 maart. Groepskorting (10+) beschikbaar via info@ahoy.nl.`,
    date: new Date("2026-04-04T13:00:00"),
    endDate: new Date("2026-04-05T23:00:00"),
    location: "Rotterdam Ahoy",
    city: "Rotterdam",
    category: "dance",
    subcategory: "urban dance",
    isPaid: true,
    price: 15,
    priceModel: "from",
    adultPrice: 15,
    kidsPrice: 8,
    familyPrice: 38,
    image: "https://images.unsplash.com/photo-1484972759836-b93f9ef2b293?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80",
      "https://images.unsplash.com/photo-1547347298-4074fc3086f0?w=800&q=80",
    ],
    tags: ["waacking", "voguing", "dancehall", "krump", "breaking"],
    vibeLabels: ["Energetic", "Urban"],
    moodTags: ["energetic"],
    capacity: 3500,
    attendeeCount: 2800,
    likeCount: 445,
    kidFriendly: true,
    familyFriendly: true,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: false,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.ahoy.nl/en/events/rotterdam-dance-festival",
    organizerBio: "Rotterdam Dance Festival organiseert jaarlijks een van de grootste dansfestivals van Europa.",
  },
  {
    title: "Afrobeats Night — Melkweg Amsterdam",
    description: `De meest swingdende nacht van Amsterdam! Afrobeats, Afro-house, Amapiano en dancehall in de historische zaal van de Melkweg. Met DJ's uit Nederland, Ghana en Nigeria en dansers die de vloer in vuur en vlam zetten.\n\n🎟️ TICKETS KOPEN:\nTickets verkrijgbaar via Melkweg.nl — €22 regulier, €18 voor Melkweg-leden. Deur open om 22:00, aanvang 22:30. Tokens voor drankjes ook online te kopen voor kortere wachttijden aan de bar.`,
    date: new Date("2026-04-11T22:00:00"),
    endDate: new Date("2026-04-12T05:00:00"),
    location: "Melkweg Amsterdam",
    city: "Amsterdam",
    category: "music",
    subcategory: "afrobeats",
    isPaid: true,
    price: 22,
    priceModel: "paid",
    adultPrice: 22,
    image: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80",
    ],
    tags: ["afrobeats", "amapiano", "dancehall", "afro-house", "nightlife"],
    vibeLabels: ["Energetic", "Urban"],
    moodTags: ["party", "energetic"],
    capacity: 800,
    attendeeCount: 750,
    likeCount: 389,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: false,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.melkweg.nl/en/agenda/afrobeats-night",
    organizerBio: "Afrobeats Night Amsterdam is de grootste recurring Afrobeats-nacht van Nederland.",
  },
  {
    title: "Breaking the Boundaries — TivoliVredenburg",
    description: `Breaking the Boundaries is een spectaculaire dansshow waarbij 40 professionele dansers de grenzen van urban dance verleggen. Gechorografeerde shows gecombineerd met spontane battles, live muziek en een DJ. Een must-see voor iedereen die van urban dance houdt.\n\n🎟️ TICKETS KOPEN:\nTickets via TivoliVredenburg.nl — Regulier €18, Studenten €14 met geldig student-ID. Vroegboekkorting 20% via de nieuwsbrief. Groepstickets (8+) via groepen@tivolivredenburg.nl.`,
    date: new Date("2026-04-25T20:00:00"),
    endDate: new Date("2026-04-25T23:30:00"),
    location: "TivoliVredenburg Utrecht",
    city: "Utrecht",
    category: "dance",
    subcategory: "show",
    isPaid: true,
    price: 18,
    priceModel: "from",
    adultPrice: 18,
    kidsPrice: 10,
    image: "https://images.unsplash.com/photo-1601152165938-76c38e4dde61?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80",
    ],
    tags: ["urban-dance", "show", "choreografie", "battle", "live"],
    vibeLabels: ["Energetic", "Creative"],
    moodTags: ["energetic", "creative"],
    capacity: 1500,
    attendeeCount: 1100,
    likeCount: 278,
    kidFriendly: true,
    familyFriendly: true,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.tivolivredenburg.nl/agenda/breaking-the-boundaries",
    organizerBio: "Cutting Edge Productions brengt spectaculaire dansshows naar theaters door heel Nederland.",
  },
  {
    title: "Beats & Rhymes Festival — 013 Tilburg",
    description: `Het beste van Nederlandse hip-hop en rap in één nacht bij poppodium 013 in Tilburg! Met optredens van de grootste namen uit de NL rap scene, open mic rondes, cypher battles en een showcase voor upcoming artists. De bar gaat open voor de beste beats van Nederland.\n\n🎟️ TICKETS KOPEN:\nTickets via 013.nl of aan de deur — €22 pre-sale, €27 aan de deur. Vroegboekkorting van 10% met code URBAN26. 013-leden betalen altijd minder — word lid via 013.nl voor €30/jaar.`,
    date: new Date("2026-05-02T19:00:00"),
    endDate: new Date("2026-05-03T02:00:00"),
    location: "013 Tilburg",
    city: "Tilburg",
    category: "music",
    subcategory: "hip-hop",
    isPaid: true,
    price: 22,
    priceModel: "paid",
    adultPrice: 22,
    image: "https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1535928148101-3c975e8c4afe?w=800&q=80",
    ],
    tags: ["hip-hop", "rap", "live", "open-mic", "cypher"],
    vibeLabels: ["Energetic", "Urban"],
    moodTags: ["energetic", "urban"],
    capacity: 900,
    attendeeCount: 720,
    likeCount: 201,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://013.nl/en/programma/beats-rhymes",
    organizerBio: "013 is het toonaangevende poppodium van Tilburg en Brabant.",
  },
  {
    title: "Breaking for Gold — Den Haag",
    description: `Een van de meest gerespecteerde breaking battles in Nederland! Breaking for Gold brengt de beste B-Boys en B-Girls uit heel Nederland naar het Paard in Den Haag. Format: 1v1, 2v2, en crew battles met internationale gastjurys. Live DJs draaien de freshste beats.\n\n🎟️ TICKETS KOPEN:\nTickets via Paard.nl — Toeschouwers €12, deelnemers inschrijven via het aanmeldformulier op bfg.nl. Early bird toeschouwerticket €8 (geldig tot 20 april). Deelnamekosten: €10 per categorie.`,
    date: new Date("2026-05-09T12:00:00"),
    endDate: new Date("2026-05-09T22:00:00"),
    location: "Paard van Troje Den Haag",
    city: "Den Haag",
    category: "dance",
    subcategory: "breaking",
    isPaid: true,
    price: 12,
    priceModel: "from",
    adultPrice: 12,
    kidsPrice: 6,
    image: "https://images.unsplash.com/photo-1598387993281-cecf8b71a8f8?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1547347298-4074fc3086f0?w=800&q=80",
    ],
    tags: ["breaking", "b-boy", "b-girl", "battle", "1v1", "crew"],
    vibeLabels: ["Energetic", "Urban"],
    moodTags: ["competitive", "energetic"],
    capacity: 800,
    attendeeCount: 620,
    likeCount: 194,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.paard.nl/agenda/breaking-for-gold",
    organizerBio: "Breaking for Gold is al 6 jaar dé breaking battle van Den Haag en omstreken.",
  },
  {
    title: "Hip-Hop in het Park — Vondelpark",
    description: `De meest gezellige gratis hip-hop dag van Amsterdam! In het hart van het Vondelpark klinken hele dag hip-hop beats, zijn er breakdance demos, freestylecirkels, beatbox battles en kunstinstallaties. Kom met de hele familie genieten van urban culture in een groene omgeving.\n\n🎟️ TICKETS KOPEN:\nVOLLEDIG GRATIS! Gewoon langskomen bij het Vondelpark open-air theater. Geen registratie nodig. Donaties voor de artiesten worden gewaardeerd.`,
    date: new Date("2026-06-20T12:00:00"),
    endDate: new Date("2026-06-20T21:00:00"),
    location: "Vondelpark Amsterdam",
    city: "Amsterdam",
    category: "music",
    subcategory: "hip-hop",
    isPaid: false,
    price: 0,
    priceModel: "free",
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1535928148101-3c975e8c4afe?w=800&q=80",
      "https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=800&q=80",
    ],
    tags: ["gratis", "hip-hop", "vondelpark", "outdoor", "familie"],
    vibeLabels: ["Chill", "Family", "Urban"],
    moodTags: ["chill", "family"],
    capacity: 5000,
    attendeeCount: 3500,
    likeCount: 677,
    kidFriendly: true,
    familyFriendly: true,
    isIndoor: false,
    crowdLevel: "medium",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.amsterdam.nl/evenementen/vondelpark",
    organizerBio: "Stichting Vrienden van het Vondelpark organiseert gratis culturele evenementen.",
  },
  {
    title: "Rotterdam Skate Jam",
    description: `De grootste skateboard jam van Rotterdam! Op het iconische Westblaak-plein komen de beste skaters van Zuid-Holland bij elkaar voor een dag vol tricks, lines en goede vibes. Beginners welkom — er zijn ook demos en try-out sessies voor nieuwkomers.\n\n🎟️ TICKETS KOPEN:\nGRATIS voor alle toeschouwers! Deelnemen? Meld je aan via skaterdamroterdam.nl. Neem je eigen board mee, of huur er een voor €5 op locatie. Deelnemers onder 12 jaar moeten bescherming dragen.`,
    date: new Date("2026-05-24T10:00:00"),
    endDate: new Date("2026-05-24T19:00:00"),
    location: "Westblaak Rotterdam",
    city: "Rotterdam",
    category: "skate",
    subcategory: "street skate",
    isPaid: false,
    price: 0,
    priceModel: "free",
    image: "https://images.unsplash.com/photo-1548515819-7463d6f88a91?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1563492065599-3520f775eeed?w=800&q=80",
    ],
    tags: ["skateboard", "street", "jam", "tricks", "outdoor"],
    vibeLabels: ["Energetic", "Urban"],
    moodTags: ["energetic", "urban"],
    capacity: 1500,
    attendeeCount: 800,
    likeCount: 256,
    kidFriendly: true,
    familyFriendly: true,
    isIndoor: false,
    crowdLevel: "medium",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: false,
    externalTicketLink: "https://www.skaterdamroterdam.nl/events/rotterdam-skate-jam",
    organizerBio: "Skaterdam Rotterdam verbindt de skate community in Rotterdam.",
  },
  {
    title: "Parkour Jam Amsterdam",
    description: `Amsterdamse parkour- en freerunning-enthousiastelingen verzamelen zich voor een dag van beweging, creativiteit en stadsverkenning. Beginners- en gevorderdensessies, clinics van professionals, en een fotosessie door de stad. Alle niveaus welkom!\n\n🎟️ TICKETS KOPEN:\nGRATIS deelname. Registreer je via Eventbrite om je plek te reserveren (beperkte plaatsen). Draag comfortabele sportkleding. Handschoenen aanbevolen voor beginners.`,
    date: new Date("2026-04-26T10:00:00"),
    endDate: new Date("2026-04-26T17:00:00"),
    location: "Amstelpark Amsterdam",
    city: "Amsterdam",
    category: "parkour",
    subcategory: "freerunning",
    isPaid: false,
    price: 0,
    priceModel: "free",
    image: "https://images.unsplash.com/photo-1571019613914-85f342c6a11e?w=800&q=80",
    gallery: [],
    tags: ["parkour", "freerunning", "urban", "sport", "outdoor"],
    vibeLabels: ["Energetic", "Urban"],
    moodTags: ["energetic"],
    capacity: 100,
    attendeeCount: 75,
    likeCount: 89,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: false,
    crowdLevel: "low",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: false,
    externalTicketLink: "https://www.eventbrite.nl/e/parkour-jam-amsterdam-2026",
    organizerBio: "Amsterdam Parkour Community brengt freerunners uit de hele stad samen.",
  },
  {
    title: "Urban Kids Festival — Familiedag",
    description: `Een fantastische dag vol urban culture voor de hele familie! Breakdance workshops voor kids (7-14 jaar), graffiti-tekenworkshops (met milieuvriendelijke verf), beatboxlessen, skateboard introductie en live muziek. Een veilige omgeving waar kinderen kennis maken met de rijke wereld van urban culture.\n\n🎟️ TICKETS KOPEN:\nTickets via Eventbrite.nl — Kind (4-12) €8, Volwassene €10, Gezinspakket (2 volwassenen + 2 kinderen) €28. Kinderen onder 4 jaar GRATIS. Reserveer van tevoren want de workshops zijn snel vol!`,
    date: new Date("2026-05-03T11:00:00"),
    endDate: new Date("2026-05-03T17:00:00"),
    location: "Cultuurpark Westergasfabriek Amsterdam",
    city: "Amsterdam",
    category: "kids",
    subcategory: "workshop",
    isPaid: true,
    price: 8,
    priceModel: "from",
    adultPrice: 10,
    kidsPrice: 8,
    familyPrice: 28,
    image: "https://images.unsplash.com/photo-1529518969858-8baa65152fc8?w=800&q=80",
    gallery: [],
    tags: ["kids", "familie", "workshop", "graffiti", "breakdance"],
    vibeLabels: ["Family", "Creative"],
    moodTags: ["family", "creative"],
    capacity: 300,
    attendeeCount: 220,
    likeCount: 198,
    kidFriendly: true,
    familyFriendly: true,
    isIndoor: false,
    crowdLevel: "medium",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.eventbrite.nl/e/urban-kids-festival-amsterdam-2026",
    organizerBio: "Urban Kids Foundation maakt urban culture toegankelijk voor kinderen door heel Nederland.",
  },
  {
    title: "Graffiti Workshop voor Kinderen",
    description: `Leer de basisvaardigheden van graffiti-art in een veilige en gecontroleerde omgeving. Professionele graffitikunstenaars leren kinderen (8-16 jaar) hoe ze hun naam kunnen stylizen, hoe ze met spraypaint werken en hoe ze een eigen design maken. Alle materialen zijn inbegrepen.\n\n🎟️ TICKETS KOPEN:\nTickets via Eventbrite — €15 per kind, inclusief alle materialen. Maximaal 20 deelnemers per sessie. Schrijf je snel in, want de plekken zijn beperkt! Ouders mogen gratis meekijken.`,
    date: new Date("2026-04-18T10:00:00"),
    endDate: new Date("2026-04-18T13:00:00"),
    location: "NDSM-werf Amsterdam Noord",
    city: "Amsterdam",
    category: "kids",
    subcategory: "workshop",
    isPaid: true,
    price: 15,
    priceModel: "paid",
    adultPrice: 0,
    kidsPrice: 15,
    image: "https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=800&q=80",
    gallery: [],
    tags: ["graffiti", "kids", "workshop", "kunst", "spraypaint"],
    vibeLabels: ["Creative", "Family"],
    moodTags: ["creative", "family"],
    capacity: 20,
    attendeeCount: 18,
    likeCount: 67,
    kidFriendly: true,
    familyFriendly: true,
    isIndoor: false,
    crowdLevel: "low",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: false,
    externalTicketLink: "https://www.eventbrite.nl/e/graffiti-workshop-kinderen-amsterdam",
    organizerBio: "Spray Art Studio geeft professionele graffiti workshops al meer dan 10 jaar.",
  },
  {
    title: "Red Bull Soundclash NL",
    description: `Red Bull Soundclash is een legendarische muziekbattle waarbij twee artiesten tegenover elkaar staan en om de gunst van het publiek strijden. De Nederlandse editie brengt de rijkste artiesten uit de NL hip-hop en dancehall scene naar AFAS Live.\n\n🎟️ TICKETS KOPEN:\nTickets via Ticketmaster.nl — €28 regulier, €45 VIP (inclusief pre-party toegang). Studenten met geldig ID betalen €22. Maximaal 4 tickets per account. Deuren open om 19:00.`,
    date: new Date("2026-05-30T20:00:00"),
    endDate: new Date("2026-05-31T02:00:00"),
    location: "AFAS Live Amsterdam",
    city: "Amsterdam",
    category: "music",
    subcategory: "battle",
    isPaid: true,
    price: 28,
    priceModel: "from",
    adultPrice: 28,
    image: "https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=800&q=80",
    gallery: [],
    tags: ["soundclash", "red-bull", "hip-hop", "dancehall", "battle"],
    vibeLabels: ["Energetic", "Urban", "Luxury"],
    moodTags: ["energetic", "party"],
    capacity: 6000,
    attendeeCount: 5200,
    likeCount: 812,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: true,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.ticketmaster.nl/event/red-bull-soundclash-nl",
    organizerBio: "Red Bull organiseert de meest iconische muziekbattles en sport events ter wereld.",
  },
  {
    title: "Utrecht Breaking Battles 2026",
    description: `TivoliVredenburg in Utrecht host de jaarlijkse Breaking Battles — een must-see voor iedereen die van breaking houdt. Met categorieën voor juniors (onder 18), adults en masters. Jury bestaat uit nationale kampioenen en internationale B-Boy legends.\n\n🎟️ TICKETS KOPEN:\nTickets via TivoliVredenburg.nl — Toeschouwerticket €12, Combiticket (deelnemer + toeschouwer) €18. Juniors deelnemen voor €5 per categorie. Online inschrijven via het evenement-pagina vereist.`,
    date: new Date("2026-04-18T11:00:00"),
    endDate: new Date("2026-04-18T21:00:00"),
    location: "TivoliVredenburg Utrecht",
    city: "Utrecht",
    category: "dance",
    subcategory: "breaking",
    isPaid: true,
    price: 12,
    priceModel: "from",
    adultPrice: 12,
    kidsPrice: 5,
    image: "https://images.unsplash.com/photo-1547347298-4074fc3086f0?w=800&q=80",
    gallery: [],
    tags: ["breaking", "b-boy", "b-girl", "battle", "junior"],
    vibeLabels: ["Energetic", "Urban"],
    moodTags: ["competitive", "energetic"],
    capacity: 700,
    attendeeCount: 580,
    likeCount: 167,
    kidFriendly: true,
    familyFriendly: true,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.tivolivredenburg.nl/agenda/utrecht-breaking-battles",
    organizerBio: "Utrecht Break Academy organiseert jaarlijks de meest gerespecteerde breaking battle van de Randstad.",
  },
  {
    title: "Conscious Vibes Festival Amsterdam",
    description: `Een festival dat urban culture en bewust leven samenbrengt op de prachtige NDSM-werf. Met muziek (neo-soul, afrobeats, jazz-hop), dansworkshops, yoga, vegan streetfood, local artisans en inspirerende speakers. Een festival voor de ziel.\n\n🎟️ TICKETS KOPEN:\nTickets via Eventbrite.nl — Dagticket €25, Weekend €40. Early bird (tot 1 mei) €18/dag. Kinderen (0-12) gratis. Maaltijden en drankjes zijn niet inbegrepen. Gratis campingplek voor reizigers van ver weg (aanmelden vereist).`,
    date: new Date("2026-06-06T12:00:00"),
    endDate: new Date("2026-06-07T22:00:00"),
    location: "NDSM-werf Amsterdam Noord",
    city: "Amsterdam",
    category: "festival",
    subcategory: "conscious",
    isPaid: true,
    price: 25,
    priceModel: "from",
    adultPrice: 25,
    kidsPrice: 0,
    familyPrice: 50,
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800&q=80",
    ],
    tags: ["festival", "conscious", "neo-soul", "yoga", "vegan"],
    vibeLabels: ["Chill", "Creative", "Urban"],
    moodTags: ["chill", "creative"],
    capacity: 2500,
    attendeeCount: 1800,
    likeCount: 334,
    kidFriendly: true,
    familyFriendly: true,
    isIndoor: false,
    crowdLevel: "medium",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.eventbrite.nl/e/conscious-vibes-festival-amsterdam-2026",
    organizerBio: "Conscious Culture Collective organiseert events die urban culture verbinden met duurzaamheid.",
  },
  {
    title: "HipHop Academy Showcase 2026",
    description: `De beste leerlingen van de meest gerenommeerde hip-hop dansscholen van Amsterdam staan op het podium! Een spectaculaire avond vol choreografieën in breaking, popping, locking, hip-hop en waacking. Studenten van 8 tot 28 jaar treden op voor vrienden, familie en de hele community.\n\n🎟️ TICKETS KOPEN:\nTickets via Eventbrite.nl — €12 regulier, €8 studenten. Leerlingen van deelnemende scholen krijgen korting met schoolpas. Tickets ook te koop aan de deur voor zover beschikbaar.`,
    date: new Date("2026-04-04T19:00:00"),
    endDate: new Date("2026-04-04T22:30:00"),
    location: "Stadsschouwburg Amsterdam",
    city: "Amsterdam",
    category: "dance",
    subcategory: "showcase",
    isPaid: true,
    price: 12,
    priceModel: "from",
    adultPrice: 12,
    kidsPrice: 6,
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80",
    gallery: [],
    tags: ["showcase", "dance-school", "popping", "locking", "waacking"],
    vibeLabels: ["Creative", "Family"],
    moodTags: ["creative", "family"],
    capacity: 500,
    attendeeCount: 420,
    likeCount: 145,
    kidFriendly: true,
    familyFriendly: true,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.eventbrite.nl/e/hiphop-academy-showcase-amsterdam-2026",
    organizerBio: "HipHop Academy Amsterdam is de grootste hip-hop dansschool van Nederland.",
  },
  {
    title: "Street Dance Battle Haarlem",
    description: `Patronaat in Haarlem host de meest gezellige regionale street dance battle van Noord-Holland. Open battle format — aanmelden ter plekke! Categorieën: Locking, Popping, Hip-Hop Freestyle, Kids (onder 16). Gastjurors uit de Amsterdam en Rotterdam scene.\n\n🎟️ TICKETS KOPEN:\nToeschouwerticket €10 via Patronaat.nl. Deelnemers betalen €5 registratiekosten aan de deur. Kom vroeg — deelnemersplaatsen zijn beperkt. Gratis drankje inbegrepen voor deelnemers.`,
    date: new Date("2026-03-28T15:00:00"),
    endDate: new Date("2026-03-28T23:00:00"),
    location: "Patronaat Haarlem",
    city: "Haarlem",
    category: "dance",
    subcategory: "street dance",
    isPaid: true,
    price: 10,
    priceModel: "from",
    adultPrice: 10,
    kidsPrice: 5,
    image: "https://images.unsplash.com/photo-1484972759836-b93f9ef2b293?w=800&q=80",
    gallery: [],
    tags: ["locking", "popping", "street-dance", "battle", "haarlem"],
    vibeLabels: ["Energetic", "Urban"],
    moodTags: ["competitive", "energetic"],
    capacity: 350,
    attendeeCount: 290,
    likeCount: 112,
    kidFriendly: true,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: false,
    externalTicketLink: "https://www.patronaat.nl/agenda/street-dance-battle",
    organizerBio: "Haarlem Dance Underground organiseert maandelijkse dance battles in Noord-Holland.",
  },
  {
    title: "Zomercarnaval Rotterdam",
    description: `De grootste Caraïbische stoet van Nederland trekt elk jaar honderdduizenden bezoekers naar de straten van Rotterdam. Samba, salsa, zouk, dancehall, soca en merengue klinken door de hele stad. Met de grootste deelname van culturele verenigingen ooit!\n\n🎟️ TICKETS KOPEN:\nDe stoet is GRATIS te bekijken langs de route. Voor de feestlocaties (binnen) variëren tickets van €5 tot €15 afhankelijk van het podium. Bekijk alle locaties via zomercarnaval.nl.`,
    date: new Date("2026-07-25T12:00:00"),
    endDate: new Date("2026-07-26T02:00:00"),
    location: "Centrum Rotterdam",
    city: "Rotterdam",
    category: "cultural",
    subcategory: "carnaval",
    isPaid: false,
    price: 0,
    priceModel: "free",
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80",
    gallery: [],
    tags: ["zomercarnaval", "cultureel", "stoet", "samba", "dancehall"],
    vibeLabels: ["Energetic", "Family", "Urban"],
    moodTags: ["party", "family", "energetic"],
    capacity: 100000,
    attendeeCount: 85000,
    likeCount: 2340,
    kidFriendly: true,
    familyFriendly: true,
    isIndoor: false,
    crowdLevel: "busy",
    isFeatured: true,
    isTrending: false,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.zomercarnaval.nl",
    organizerBio: "Stichting Zomercarnaval organiseert al 50+ jaar het grootste Caraïbische festival van Nederland.",
  },
  {
    title: "Amsterdam Dance Event — Urban Nights",
    description: `ADE Urban Nights is de urban culture tak van het wereldberoemde Amsterdam Dance Event. Met de beste urban DJ's en producers uit Nederland en de wereld, exclusieve showcases, afterparties en industry panels over de toekomst van urban music.\n\n🎟️ TICKETS KOPEN:\nTickets via ADE.nl — Dagpass €35, 5-daags Festival Pass €120. VIP Experience (inclusief panels & loungeaccess) €195. Early bird tot 1 augustus met 20% korting. ADE Koers voor professionals: aparte registratie vereist.`,
    date: new Date("2026-10-17T20:00:00"),
    endDate: new Date("2026-10-18T06:00:00"),
    location: "Melkweg & Paradiso Amsterdam",
    city: "Amsterdam",
    category: "music",
    subcategory: "electronic urban",
    isPaid: true,
    price: 35,
    priceModel: "from",
    adultPrice: 35,
    image: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80",
    ],
    tags: ["ADE", "urban", "DJ", "nachtleven", "amsterdam"],
    vibeLabels: ["Energetic", "Urban", "Luxury"],
    moodTags: ["party", "energetic"],
    capacity: 5000,
    attendeeCount: 4200,
    likeCount: 956,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: true,
    isTrending: false,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.ade.nl/tickets",
    organizerBio: "Amsterdam Dance Event is het grootste club music festival en conferentie ter wereld.",
  },
  {
    title: "Tilburg Urban Festival — 013",
    description: `013 Tilburg presenteert het Urban Festival met optredens van de sterkste namen uit de Brabantse en nationale hip-hop en r&b scene. Drie podia, meer dan 20 acts, foodtrucks, merchandise en een open mic sessie om nieuwe talenten te spotten.\n\n🎟️ TICKETS KOPEN:\nTickets via 013.nl — Vroegboekers €20 (beperkt), Regulier €25, Deur €30. 013-Leden: 15% korting met ledenpas. Groepskorting voor 10+ personen via info@013.nl.`,
    date: new Date("2026-06-13T16:00:00"),
    endDate: new Date("2026-06-14T03:00:00"),
    location: "013 Tilburg",
    city: "Tilburg",
    category: "festival",
    subcategory: "urban",
    isPaid: true,
    price: 25,
    priceModel: "paid",
    adultPrice: 25,
    image: "https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=800&q=80",
    gallery: [],
    tags: ["festival", "hip-hop", "r&b", "live", "tilburg"],
    vibeLabels: ["Energetic", "Urban"],
    moodTags: ["energetic", "urban"],
    capacity: 2000,
    attendeeCount: 1600,
    likeCount: 287,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://013.nl/en/programma/tilburg-urban-festival",
    organizerBio: "013 is het toonaangevende poppodium van Tilburg.",
  },
  {
    title: "Street Culture Night — Paard Den Haag",
    description: `Een nacht vol urban culture in het historische Paard in Den Haag. Hip-hop, dancehall, grime en afrobeats wisselen elkaar af op twee podia. Met opkomende DJ's uit Den Haag en Rotterdam, en live graffiti artwork door lokale artists.\n\n🎟️ TICKETS KOPEN:\nTickets via Paard.nl — €15 voorverkoop, €18 aan de deur. Studenten €12 met geldig studentenkaart. Deuren open 22:00. Dresscode: Urban & Streetwear.`,
    date: new Date("2026-06-27T22:00:00"),
    endDate: new Date("2026-06-28T05:00:00"),
    location: "Paard Den Haag",
    city: "Den Haag",
    category: "nightlife",
    subcategory: "urban",
    isPaid: true,
    price: 15,
    priceModel: "paid",
    adultPrice: 15,
    image: "https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=800&q=80",
    gallery: [],
    tags: ["nightlife", "hip-hop", "dancehall", "grime", "den-haag"],
    vibeLabels: ["Energetic", "Urban"],
    moodTags: ["party", "energetic"],
    capacity: 600,
    attendeeCount: 520,
    likeCount: 178,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: false,
    externalTicketLink: "https://www.paard.nl/agenda/street-culture-night",
    organizerBio: "The Hague Urban Collective organiseert maandelijkse urban culture events in Den Haag.",
  },
  {
    title: "Breakdance World Cup Qualifier — Rotterdam",
    description: `De Nederlandse kwalificatieronde voor de Breakdance World Cup! De top-32 B-Boys en B-Girls van Nederland strijden voor een plek in de internationale finale. Met live battles, jury uit Parijs en een publieksprijs. De winnaar vliegt naar de World Cup finale!\n\n🎟️ TICKETS KOPEN:\nToeschouwertickets via Ahoy.nl — €18 regulier, €12 studenten. Deelnemers moeten zich registreren via bwc-nederland.nl. Inschrijfgeld deelname: €15. Aanmeldingen sluiten 1 juni. Wacht niet te lang!`,
    date: new Date("2026-06-20T10:00:00"),
    endDate: new Date("2026-06-20T22:00:00"),
    location: "Rotterdam Ahoy",
    city: "Rotterdam",
    category: "dance",
    subcategory: "breaking",
    isPaid: true,
    price: 18,
    priceModel: "from",
    adultPrice: 18,
    kidsPrice: 8,
    image: "https://images.unsplash.com/photo-1598387993281-cecf8b71a8f8?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1547347298-4074fc3086f0?w=800&q=80",
    ],
    tags: ["breaking", "world-cup", "qualifier", "competitie", "b-boy"],
    vibeLabels: ["Energetic", "Urban"],
    moodTags: ["competitive", "energetic"],
    capacity: 2000,
    attendeeCount: 1500,
    likeCount: 423,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: false,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.ahoy.nl/en/events/breakdance-world-cup-qualifier",
    organizerBio: "Breakdance Nederland Bond is de officiële organisatie van breaking wedstrijden in Nederland.",
  },
  {
    title: "Family Dance Workshop — Haarlem",
    description: `Een gezellige dansmiddag voor het hele gezin! Ouders en kinderen leren samen de basics van hip-hop, funk en disco. Geen ervaring nodig — onze instructeurs begeleiden iedereen stap voor stap. Inclusief drankjes en een kleine snack.\n\n🎟️ TICKETS KOPEN:\nTickets via Eventbrite.nl — €12 per volwassene, €8 per kind (4-12 jaar), kinderen onder 4 jaar gratis. Gezinspakket (2 vol. + 2 kids) €32. Schrijf je in voor 20 april voor 10% korting.`,
    date: new Date("2026-04-12T14:00:00"),
    endDate: new Date("2026-04-12T17:00:00"),
    location: "De Philharmonie Haarlem",
    city: "Haarlem",
    category: "workshop",
    subcategory: "family dance",
    isPaid: true,
    price: 12,
    priceModel: "from",
    adultPrice: 12,
    kidsPrice: 8,
    familyPrice: 32,
    image: "https://images.unsplash.com/photo-1529518969858-8baa65152fc8?w=800&q=80",
    gallery: [],
    tags: ["workshop", "familie", "hip-hop", "dans", "kids"],
    vibeLabels: ["Family", "Chill"],
    moodTags: ["family", "chill"],
    capacity: 60,
    attendeeCount: 48,
    likeCount: 94,
    kidFriendly: true,
    familyFriendly: true,
    isIndoor: true,
    crowdLevel: "low",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: false,
    externalTicketLink: "https://www.eventbrite.nl/e/family-dance-workshop-haarlem-2026",
    organizerBio: "Dance Together biedt toegankelijke danslessen voor families door heel Nederland.",
  },
  {
    title: "Lowlands Urban Stage 2026",
    description: `Het iconische Lowlands Festival heeft een speciale Urban Stage voor drie dagen puur urban culture. Hip-hop, trap, drill, afrobeats, grime en dancehall van de beste nationale en internationale acts. Dit is het festival dat je niet mag missen dit jaar!\n\n🎟️ TICKETS KOPEN:\nTickets via Lowlands.nl — Weekend €225 (inclusief camping), Dagticket €95. Early bird uitverkocht, maar wachtlijst beschikbaar. Check Ticketswap voor doorverkoop. Parking €20/dag apart te boeken.`,
    date: new Date("2026-08-14T12:00:00"),
    endDate: new Date("2026-08-16T23:00:00"),
    location: "Walibi Holland Biddinghuizen",
    city: "Biddinghuizen",
    category: "festival",
    subcategory: "multi-genre",
    isPaid: true,
    price: 225,
    priceModel: "from",
    adultPrice: 225,
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=800&q=80",
    ],
    tags: ["lowlands", "festival", "urban", "hip-hop", "camping"],
    vibeLabels: ["Energetic", "Urban", "Luxury"],
    moodTags: ["party", "energetic"],
    capacity: 55000,
    attendeeCount: 48000,
    likeCount: 4521,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: false,
    crowdLevel: "busy",
    isFeatured: true,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.lowlands.nl/tickets",
    organizerBio: "Mojo Concerts organiseert Lowlands al meer dan 30 jaar.",
  },
  {
    title: "Eindhoven Urban Beats",
    description: `Eindhoven pulsates met de beste urban beats! In Effenaar — het meest innovatieve poppodium van Brabant — worden drie zalen gevuld met hip-hop, grime, drill en r&b. Spotlight op lokale Eindhovense acts naast regionale headliners.\n\n🎟️ TICKETS KOPEN:\nTickets via Effenaar.nl — €20 voorverkoop, €25 aan de deur. Studenten TU/e en Fontys: €15 met campuscard. Vroegboekertickiet (t/m 1 april) voor €16. Parkeer gratis op P+R terreinen en loop 10 min.`,
    date: new Date("2026-05-16T19:00:00"),
    endDate: new Date("2026-05-17T03:00:00"),
    location: "Effenaar Eindhoven",
    city: "Eindhoven",
    category: "music",
    subcategory: "hip-hop",
    isPaid: true,
    price: 20,
    priceModel: "paid",
    adultPrice: 20,
    image: "https://images.unsplash.com/photo-1535928148101-3c975e8c4afe?w=800&q=80",
    gallery: [],
    tags: ["hip-hop", "grime", "drill", "r&b", "eindhoven"],
    vibeLabels: ["Energetic", "Urban"],
    moodTags: ["energetic", "urban"],
    capacity: 1200,
    attendeeCount: 950,
    likeCount: 213,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.effenaar.nl/agenda/eindhoven-urban-beats",
    organizerBio: "Effenaar is het toonaangevende poppodium van Eindhoven en Brabant.",
  },
  {
    title: "Krump Battle NL — Zuiderparktheater",
    description: `De meest intense dansstrijd van Nederland: Krump Battle NL! Krump is een expressieve, krachtige dansstijl die zijn roots heeft in de Afro-Amerikaanse gemeenschap. De beste Krumpers van Nederland strijden voor de nationale titel in het Zuiderparktheater in Rotterdam.\n\n🎟️ TICKETS KOPEN:\nToeschouwertickets €12 via Eventbrite.nl. Deelnemers aanmelden via krumpnl.nl — €8 inschrijfgeld. Categorieën: Junior (t/m 17), Adult. Battles starten exact op tijd, zorg voor een vroege aankomst.`,
    date: new Date("2026-05-23T14:00:00"),
    endDate: new Date("2026-05-23T21:00:00"),
    location: "Zuiderparktheater Rotterdam",
    city: "Rotterdam",
    category: "dance",
    subcategory: "krump",
    isPaid: true,
    price: 12,
    priceModel: "from",
    adultPrice: 12,
    kidsPrice: 6,
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80",
    gallery: [],
    tags: ["krump", "battle", "urban", "expressie", "rotterdam"],
    vibeLabels: ["Energetic", "Urban"],
    moodTags: ["competitive", "energetic"],
    capacity: 400,
    attendeeCount: 320,
    likeCount: 138,
    kidFriendly: true,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: false,
    externalTicketLink: "https://www.eventbrite.nl/e/krump-battle-nl-rotterdam-2026",
    organizerBio: "Krump Nederland Community brengt de Krump scene in Nederland samen.",
  },
  {
    title: "Graffiti & Street Art Tour Amsterdam",
    description: `Ontdek de verborgen graffiti-paareltjes van Amsterdam op een begeleide wandeltour! Een professionele gids neemt je mee langs de mooiste murals, tags, en street art installaties van de stad. Leer over de kunstenaars, de betekenis achter de werken en de geschiedenis van Amsterdamse straatcultuur.\n\n🎟️ TICKETS KOPEN:\nTickets via Airbnb Experiences of direct via graffitiamsterdam.nl — €18 per persoon. Kleine groepen (max 12 personen). Privétour beschikbaar voor groepen €150. Elke zaterdag om 14:00 en 16:00. Aanmelden verplicht.`,
    date: new Date("2026-04-05T14:00:00"),
    endDate: new Date("2026-04-05T16:00:00"),
    location: "Startpunt: NDSM Amsterdam Noord",
    city: "Amsterdam",
    category: "art",
    subcategory: "tour",
    isPaid: true,
    price: 18,
    priceModel: "paid",
    adultPrice: 18,
    kidsPrice: 10,
    image: "https://images.unsplash.com/photo-1526327760257-75f515b7a5c3?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800&q=80",
      "https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=800&q=80",
    ],
    tags: ["graffiti", "street-art", "tour", "wandeling", "cultuur"],
    vibeLabels: ["Creative", "Chill"],
    moodTags: ["creative", "chill"],
    capacity: 12,
    attendeeCount: 10,
    likeCount: 76,
    kidFriendly: true,
    familyFriendly: true,
    isIndoor: false,
    crowdLevel: "low",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: false,
    externalTicketLink: "https://www.graffitiamsterdam.nl/tours",
    organizerBio: "Graffiti Amsterdam Tours organiseert wekelijkse street art tours door Amsterdam.",
  },
  // ── MUSIC EVENTS (with musicGenre) ──────────────────────────────────────────

  // ELECTRONIC / EDM
  {
    title: "Awakenings Festival 2026 – Gashouder Amsterdam",
    description: `Awakenings Festival keert terug naar de iconische Gashouder van Westergasfabriek Amsterdam. Dit internationale techno-festival brengt de wereldtop op het gebied van elektronische muziek samen voor een onvergetelijk weekend.\n\nArtistenlineup: Charlotte de Witte, Reinier Zonneveld, Amelie Lens, Boris Brejcha, Monika Kruse, Paula Temple, en vele anderen.\n\n🎟️ TICKETS: Verkrijgbaar via awakenings.com. Day tickets €45-€55, weekend combi €85. Vroegboekkorting beschikbaar voor members.`,
    date: new Date("2026-06-12T16:00:00"),
    endDate: new Date("2026-06-14T07:00:00"),
    location: "Gashouder, Westergasfabriek Amsterdam",
    city: "Amsterdam",
    category: "festival",
    subcategory: "electronic",
    musicGenre: "electronic",
    isPaid: true,
    price: 55,
    priceModel: "from",
    adultPrice: 55,
    image: "https://images.unsplash.com/photo-1526090169837-cb4e3f6c5c36?w=800&q=80",
    tags: ["techno", "electronic", "festival", "awakenings"],
    vibeLabels: ["Energetic", "Urban"],
    moodTags: ["energetic", "urban"],
    capacity: 5000,
    attendeeCount: 4200,
    likeCount: 1820,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: false,
    crowdLevel: "busy",
    isFeatured: true,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.awakenings.com/event/festival-2026",
    organizerBio: "Awakenings is een van de meest gerespecteerde namen in de techno-wereld.",
  },
  {
    title: "DGTL Amsterdam 2026 – Elektronisch Festival",
    description: `DGTL Festival is terug op het NDSM-werf in Amsterdam-Noord. Het duurzaamste elektronische festival van Nederland met een indrukwekkend kunstprogramma, culinaire belevenissen en de beste elektronische muziek.\n\nArtistenlineup: Maceo Plex, Peggy Gou, DJ Tennis, Mathew Jonson, Yotto, Âme live.\n\n🌱 DUURZAAMHEID: DGTL streeft naar 100% circulaire productie. Vegan foodzone, bioplastic-vrij.\n\n🎟️ TICKETS: dag €69, weekend €120 via dgtl.nl`,
    date: new Date("2026-04-02T16:00:00"),
    endDate: new Date("2026-04-04T08:00:00"),
    location: "NDSM Werf, Amsterdam-Noord",
    city: "Amsterdam",
    category: "festival",
    subcategory: "electronic",
    musicGenre: "electronic",
    isPaid: true,
    price: 69,
    priceModel: "from",
    adultPrice: 69,
    image: "https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=800&q=80",
    tags: ["electronic", "techno", "house", "festival", "duurzaam"],
    vibeLabels: ["Energetic", "Urban"],
    moodTags: ["energetic", "urban"],
    capacity: 8000,
    attendeeCount: 7500,
    likeCount: 2340,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: false,
    crowdLevel: "busy",
    isFeatured: true,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.dgtl.nl/amsterdam",
    organizerBio: "DGTL is pionier in duurzame festivalproductie en elektronische muziek.",
  },
  {
    title: "Dekmantel Festival 2026 – Amsterdamse Bos",
    description: `Dekmantel Festival neemt je mee op een muzikale reis door de Amsterdamse Bos. House, techno, jazz en experimentele elektronische muziek komen samen op vijf stages omgeven door prachtige natuur.\n\nDekmantel staat bekend om zijn zorgvuldig samengestelde lineups en unieke sfeer – een weekend van muzikale ontdekking.\n\n🎟️ TICKETS: via dekmantel.com. Tickets uitverkocht binnen minuten bij release.`,
    date: new Date("2026-07-30T12:00:00"),
    endDate: new Date("2026-08-02T08:00:00"),
    location: "Amsterdamse Bos, Amsterdam",
    city: "Amsterdam",
    category: "festival",
    subcategory: "electronic",
    musicGenre: "electronic",
    isPaid: true,
    price: 75,
    priceModel: "from",
    adultPrice: 75,
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
    tags: ["house", "techno", "jazz", "electronic", "festival"],
    vibeLabels: ["Chill", "Creative"],
    moodTags: ["chill", "creative"],
    capacity: 7000,
    attendeeCount: 6800,
    likeCount: 3100,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: false,
    crowdLevel: "busy",
    isFeatured: true,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.dekmantel.com/festival",
    organizerBio: "Dekmantel is een van de meest gerespecteerde namen in de internationale elektronische muziekscene.",
  },
  {
    title: "Amsterdam Dance Event (ADE) 2026 – Conferentie & Festival",
    description: `Amsterdam Dance Event is het grootste club festival en meest invloedrijke conferentie ter wereld op het gebied van elektronische muziek. Vijf dagen lang vullen meer dan 600 artiesten honderden Amsterdamse venues.\n\nADE omvat een professionele conferentie voor de muziekindustrie, tientallen showcases, paneldiscussies en netwerkevenementen.\n\n🎵 GENRES: Techno, House, Ambient, Experimental, Deep House, Minimal\n\n🎟️ TICKETS: Sommige events gratis, andere tot €25 via ade.nl`,
    date: new Date("2026-10-14T12:00:00"),
    endDate: new Date("2026-10-18T23:59:00"),
    location: "Heel Amsterdam – Paradiso, Melkweg, Shelter, Shelter, Panama & meer",
    city: "Amsterdam",
    category: "festival",
    subcategory: "electronic",
    musicGenre: "electronic",
    isPaid: false,
    price: 0,
    priceModel: "free",
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80",
    tags: ["electronic", "techno", "house", "ADE", "conferentie"],
    vibeLabels: ["Urban", "Energetic"],
    moodTags: ["urban", "energetic"],
    capacity: 400000,
    attendeeCount: 350000,
    likeCount: 12500,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: true,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.amsterdam-dance-event.nl",
    organizerBio: "ADE is het grootste en meest invloedrijke elektronische muziekfestival ter wereld.",
  },
  {
    title: "Shelter Amsterdam – Techno Nacht met Reinier Zonneveld",
    description: `Shelter Amsterdam – het iconische undergroundclub onder de A'DAM Toren – presenteert een speciale techno nacht met Reinier Zonneveld. De Amsterdamse producer en DJ staat bekend om zijn verbluffende live sets waarbij hij zijn eigen productieswerk draait.\n\nOpeners: Alignment, Lilly Palmer.\n\n🎟️ TICKETS: €22,50 via Shelter Amsterdam. Deuren open 23:00.`,
    date: new Date("2026-03-28T23:00:00"),
    endDate: new Date("2026-03-29T08:00:00"),
    location: "Shelter Amsterdam, A'DAM Toren, Amsterdam-Noord",
    city: "Amsterdam",
    category: "nightlife",
    subcategory: "electronic",
    musicGenre: "electronic",
    isPaid: true,
    price: 22,
    priceModel: "paid",
    adultPrice: 22,
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80",
    tags: ["techno", "club", "nachtleven", "underground"],
    vibeLabels: ["Energetic", "Urban"],
    moodTags: ["energetic", "urban"],
    capacity: 800,
    attendeeCount: 700,
    likeCount: 560,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: false,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.shelteramsterdam.nl",
    organizerBio: "Shelter is een van de meest invloedrijke clubs in de Nederlandse elektronische muziekscene.",
  },

  // HIP-HOP / RAP
  {
    title: "Amsterdam Hip-Hop Summit 2026 – Melkweg",
    description: `Het jaarlijkse Amsterdam Hip-Hop Summit brengt nationale en internationale hip-hop artiesten samen op het podium van de Melkweg. Met workshops, battles, cyphers en live performances is dit hét event voor de hip-hop community.\n\nLineup: Sevn Alias, Donnie, Bizzey, Mula B, Boef, en internationale gasten.\n\n🎤 ACTIVITEITEN: Freestyle battle, graffiti live art, b-boy showcase, DJ workshop\n\n🎟️ TICKETS: €25 via ticketmaster.nl`,
    date: new Date("2026-05-16T14:00:00"),
    endDate: new Date("2026-05-16T23:00:00"),
    location: "Melkweg, Amsterdam",
    city: "Amsterdam",
    category: "music",
    subcategory: "hiphop",
    musicGenre: "hiphop",
    isPaid: true,
    price: 25,
    priceModel: "paid",
    adultPrice: 25,
    image: "https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=800&q=80",
    tags: ["hiphop", "rap", "battle", "dutch-rap", "melkweg"],
    vibeLabels: ["Urban", "Energetic"],
    moodTags: ["urban", "energetic"],
    capacity: 1500,
    attendeeCount: 1200,
    likeCount: 870,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: true,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.melkweg.nl/nl/agenda",
    organizerBio: "Melkweg is een van de meest iconische cultuurpodiums van Amsterdam.",
  },
  {
    title: "Sevn Alias & Gasten – Sold Out Tour 2026, AFAS Live",
    description: `Sevn Alias brengt zijn succesvolle 2026-tour naar AFAS Live in Amsterdam. Na zijn uitverkochte shows door heel Nederland brengt hij samen met speciale gasten een onvergetelijke avond vol Nederlandse strapmuziek en urban hiphop.\n\nSpeciale gasten worden nog aangekondigd. Vorige edities: Bizzey, Lijpe, Yung Felix.\n\n🎟️ TICKETS: €35-45 via ticketmaster.nl – Limited seated options available.`,
    date: new Date("2026-04-25T20:00:00"),
    endDate: new Date("2026-04-25T23:30:00"),
    location: "AFAS Live, Amsterdam-Oost",
    city: "Amsterdam",
    category: "music",
    subcategory: "hiphop",
    musicGenre: "hiphop",
    isPaid: true,
    price: 35,
    priceModel: "from",
    adultPrice: 35,
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80",
    tags: ["hiphop", "trap", "dutch-rap", "concert", "afas-live"],
    vibeLabels: ["Urban", "Energetic"],
    moodTags: ["urban", "energetic"],
    capacity: 6000,
    attendeeCount: 5500,
    likeCount: 2100,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: false,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.afaslive.nl",
    organizerBio: "AFAS Live is een toonaangevend poppodium in Amsterdam.",
  },
  {
    title: "Gratis Hip-Hop Cypher – Vondelpark Amsterdam",
    description: `Elke zondag komen rappers, beatboxers en b-boys samen in het Vondelpark voor een openlucht cypher. Iedereen is welkom om mee te doen of gewoon te luisteren en te genieten van de spontane urbane cultuur.\n\nDJ sets van lokale DJ's, freestyle rap, en af en toe een verrassingsoptreden van bekende Nederlandse artiesten.\n\n🎤 DEELNAME: Gratis, gewoon opdagen!\n🌤️ Doorgaat bij droog weer`,
    date: new Date("2026-05-31T14:00:00"),
    endDate: new Date("2026-05-31T18:00:00"),
    location: "Vondelpark, Amsterdam",
    city: "Amsterdam",
    category: "community",
    subcategory: "hiphop",
    musicGenre: "hiphop",
    isPaid: false,
    price: 0,
    priceModel: "free",
    image: "https://images.unsplash.com/photo-1598387993441-a364f854c3e1?w=800&q=80",
    tags: ["hiphop", "cypher", "freestyle", "gratis", "vondelpark"],
    vibeLabels: ["Urban", "Chill"],
    moodTags: ["urban", "chill"],
    capacity: 200,
    attendeeCount: 80,
    likeCount: 145,
    kidFriendly: true,
    familyFriendly: true,
    isIndoor: false,
    crowdLevel: "medium",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: false,
    externalTicketLink: null as any,
    organizerBio: "Wekelijkse community cypher in het Vondelpark.",
  },
  {
    title: "Rotterdam Hip-Hop Festival – Wilhelminapier",
    description: `Rotterdam Hip-Hop Festival op de Wilhelminapier brengt het beste van lokale en nationale hip-hop, rap, en urban cultuur naar de havens van Rotterdam. Met 3 stages, graffiti live art, streetwear markt en food trucks.\n\nLineup: Boef, Yung Nnelg, Frenna, 3robi, en many more.\n\n🎟️ TICKETS: €20 advance / €25 door – via Eventbrite Rotterdam`,
    date: new Date("2026-06-27T13:00:00"),
    endDate: new Date("2026-06-27T23:00:00"),
    location: "Wilhelminapier, Rotterdam",
    city: "Rotterdam",
    category: "festival",
    subcategory: "hiphop",
    musicGenre: "hiphop",
    isPaid: true,
    price: 20,
    priceModel: "from",
    adultPrice: 20,
    image: "https://images.unsplash.com/photo-1465225314224-587cd83d322b?w=800&q=80",
    tags: ["hiphop", "festival", "rotterdam", "rap", "urban"],
    vibeLabels: ["Urban", "Energetic"],
    moodTags: ["urban", "energetic"],
    capacity: 5000,
    attendeeCount: 3800,
    likeCount: 1560,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: false,
    crowdLevel: "busy",
    isFeatured: true,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.eventbrite.nl/e/rotterdam-hiphop-festival-2026",
    organizerBio: "Rotterdam Hip-Hop Festival is het grootste hip-hop event van Zuid-Holland.",
  },

  // R&B / SOUL
  {
    title: "Soul & R&B Night – Paradiso Amsterdam",
    description: `Paradiso presenteert een exclusieve Soul & R&B avond met internationale headliners en lokale talenten. Van neo-soul tot classic R&B, van funk tot contemporaine urban soul – een avond voor pure muziekliefhebbers.\n\nHeadliner: Lucky Daye (VS). Support: Alina Baraz, Masego. Opening: Amsterdam's finest R&B talent.\n\n🎟️ TICKETS: €32,50 via paradiso.nl. Deuren open 20:00, show 21:00.`,
    date: new Date("2026-09-12T20:00:00"),
    endDate: new Date("2026-09-12T23:30:00"),
    location: "Paradiso Amsterdam, Weteringschans 6",
    city: "Amsterdam",
    category: "music",
    subcategory: "rnb",
    musicGenre: "rnb",
    isPaid: true,
    price: 32,
    priceModel: "paid",
    adultPrice: 32,
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80",
    tags: ["rnb", "soul", "funk", "concert", "paradiso"],
    vibeLabels: ["Chill", "Luxury"],
    moodTags: ["chill", "luxury"],
    capacity: 1500,
    attendeeCount: 1200,
    likeCount: 890,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: false,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.paradiso.nl",
    organizerBio: "Paradiso is een iconisch poppodium in Amsterdam, gevestigd in een voormalige kerk.",
  },
  {
    title: "R&B Vibes Rotterdam – Rotown",
    description: `R&B Vibes is een maandelijkse club nacht in het gezellige Rotown in Rotterdam. Gespecialiseerd in de beste R&B, soul, en neo-soul van de afgelopen 30 jaar, gecombineerd met actuele urbane R&B.\n\nResidency DJ's: DJ Soulful, Mx. Aaralyn. Maandelijks wisselen de optredende artiesten.\n\n🎟️ TICKETS: €12,50 online / €15 aan de deur via rotown.nl`,
    date: new Date("2026-04-17T22:00:00"),
    endDate: new Date("2026-04-18T04:00:00"),
    location: "Rotown, Rotterdam",
    city: "Rotterdam",
    category: "nightlife",
    subcategory: "rnb",
    musicGenre: "rnb",
    isPaid: true,
    price: 12,
    priceModel: "from",
    adultPrice: 12,
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80",
    tags: ["rnb", "soul", "club", "rotterdam", "nachtleven"],
    vibeLabels: ["Chill", "Luxury"],
    moodTags: ["chill", "luxury"],
    capacity: 400,
    attendeeCount: 320,
    likeCount: 245,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.rotown.nl",
    organizerBio: "Rotown is een van de meest geliefde popcafés van Rotterdam.",
  },
  {
    title: "Smooth Sunday – Gratis R&B Brunch, De Pijp Amsterdam",
    description: `Elke laatste zondag van de maand organiseert café Louie in De Pijp een gratis R&B brunch. Live DJ sets met smooth R&B en soul terwijl je geniet van een uitgebreid brunch-menu.\n\nBrunch: 10:00-14:00 | DJ set: 11:00-15:00\n\n🥞 Inclusief gratis verse jus d'orange bij aankomst\n🎵 Muziek: Classic R&B, Neo-Soul, Lo-fi Hip-Hop\n\n🆓 GRATIS – Reserveer een tafel via de website`,
    date: new Date("2026-04-26T10:00:00"),
    endDate: new Date("2026-04-26T15:00:00"),
    location: "Café Louie, De Pijp, Amsterdam",
    city: "Amsterdam",
    category: "food",
    subcategory: "rnb",
    musicGenre: "rnb",
    isPaid: false,
    price: 0,
    priceModel: "free",
    image: "https://images.unsplash.com/photo-1428515613728-6b4607e44363?w=800&q=80",
    tags: ["rnb", "brunch", "gratis", "de-pijp", "soul"],
    vibeLabels: ["Chill", "Family"],
    moodTags: ["chill", "family"],
    capacity: 60,
    attendeeCount: 45,
    likeCount: 78,
    kidFriendly: false,
    familyFriendly: true,
    isIndoor: true,
    crowdLevel: "medium",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: false,
    externalTicketLink: null as any,
    organizerBio: "Café Louie organiseert maandelijkse R&B brunches in De Pijp.",
  },

  // JAZZ
  {
    title: "North Sea Jazz Festival 2026 – Rotterdam Ahoy",
    description: `North Sea Jazz is het grootste jazz festival ter wereld. Drie dagen lang brengt het festival de absolute top van jazz, soul, funk, blues en world music naar Rotterdam Ahoy.\n\nHeadliners: Cécile McLorin Salvant, Robert Glasper Experiment, Herbie Hancock, Dianne Reeves, Gregory Porter, Kamaal Williams.\n\nMeer dan 1.000 muzikanten op 15 podia.\n\n🎟️ TICKETS: Dag ticket €95-125, weekend €260 via northseajazz.com`,
    date: new Date("2026-07-10T12:00:00"),
    endDate: new Date("2026-07-12T23:00:00"),
    location: "Rotterdam Ahoy, Ahoy-weg 10, Rotterdam",
    city: "Rotterdam",
    category: "festival",
    subcategory: "jazz",
    musicGenre: "jazz",
    isPaid: true,
    price: 95,
    priceModel: "from",
    adultPrice: 95,
    image: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&q=80",
    tags: ["jazz", "soul", "funk", "blues", "festival", "northseajazz"],
    vibeLabels: ["Luxury", "Chill"],
    moodTags: ["luxury", "chill"],
    capacity: 70000,
    attendeeCount: 65000,
    likeCount: 12000,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: true,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.northseajazz.com",
    organizerBio: "North Sea Jazz is het grootste binnenshuis jazzfestival ter wereld.",
  },
  {
    title: "Bimhuis Jazz Sessions – Open Podium Amsterdam",
    description: `Het Bimhuis, het meest internationale jazzpodium van Nederland, organiseert wekelijkse open podium sessies. Professionele en aankomende muzikanten komen samen voor improvisatie, jam sessies en verrassende combinaties.\n\nElke vrijdagavond: open podium voor aangemelde muzikanten\nElke zaterdag: curated concert programma\n\n🎵 GENRES: Contemporary Jazz, Free Jazz, Bebop, Fusion, Experimental\n\n🎟️ TICKETS: Open podium gratis | Curated €18-28 via bimhuis.com`,
    date: new Date("2026-04-10T20:30:00"),
    endDate: new Date("2026-04-10T23:30:00"),
    location: "Bimhuis Amsterdam, Piet Heinkade 3",
    city: "Amsterdam",
    category: "music",
    subcategory: "jazz",
    musicGenre: "jazz",
    isPaid: false,
    price: 0,
    priceModel: "free",
    image: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&q=80",
    tags: ["jazz", "open-podium", "improvisatie", "bimhuis"],
    vibeLabels: ["Chill", "Creative"],
    moodTags: ["chill", "creative"],
    capacity: 230,
    attendeeCount: 180,
    likeCount: 340,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "medium",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.bimhuis.com",
    organizerBio: "Bimhuis is het meest internationale jazzpodium van Nederland.",
  },
  {
    title: "Gratis Jazz in het Park – Westerpark Amsterdam",
    description: `Elke zomer organiseert Westerpark een reeks gratis jazzoptredens in het groene hart van Amsterdam-West. Lokale jazzbands spelen repertoire van swing tot moderne jazz, terwijl bezoekers genieten van de zon in het park.\n\nProgramma: 14:00 - jazz quartet | 15:30 - vocal jazz | 17:00 - big band jam\n\n🆓 GRATIS – Gewoon komen!\n🌳 Breng een picknickdeken mee`,
    date: new Date("2026-06-20T14:00:00"),
    endDate: new Date("2026-06-20T18:00:00"),
    location: "Westerpark, Amsterdam",
    city: "Amsterdam",
    category: "community",
    subcategory: "jazz",
    musicGenre: "jazz",
    isPaid: false,
    price: 0,
    priceModel: "free",
    image: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&q=80",
    tags: ["jazz", "gratis", "park", "picknick", "westerpark"],
    vibeLabels: ["Chill", "Family"],
    moodTags: ["chill", "family"],
    capacity: 500,
    attendeeCount: 200,
    likeCount: 167,
    kidFriendly: true,
    familyFriendly: true,
    isIndoor: false,
    crowdLevel: "medium",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: false,
    externalTicketLink: null as any,
    organizerBio: "Westerpark organiseert gratis culturele evenementen voor de buurt.",
  },

  // AFROBEATS
  {
    title: "Afrovibes Festival 2026 – Theater Zuidplein Rotterdam",
    description: `Afrovibes Festival is het grootste Afrikaans culturele festival in Nederland. Van Afrobeats tot highlife, van ndombolo tot amapiano – een explosieve mix van Afrikaanse muziek, dans, mode en kunst.\n\nArtiesten: Afrobeats DJ's uit heel Europa en Afrika, live bands uit Nigeria, Ghana, Senegal en Congo.\n\n🌍 ACTIVITEITEN: Afrikaanse mode show, streetfood market, workshops, kinderatelier\n\n🎟️ TICKETS: €15 online / €18 deur via afrovibes.nl`,
    date: new Date("2026-09-26T12:00:00"),
    endDate: new Date("2026-09-27T23:00:00"),
    location: "Theater Zuidplein, Rotterdam-Zuid",
    city: "Rotterdam",
    category: "festival",
    subcategory: "afrobeats",
    musicGenre: "afrobeats",
    isPaid: true,
    price: 15,
    priceModel: "from",
    adultPrice: 15,
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80",
    tags: ["afrobeats", "afro", "festival", "rotterdam", "dans"],
    vibeLabels: ["Energetic", "Family"],
    moodTags: ["energetic", "family"],
    capacity: 3000,
    attendeeCount: 2500,
    likeCount: 1870,
    kidFriendly: true,
    familyFriendly: true,
    isIndoor: false,
    crowdLevel: "busy",
    isFeatured: true,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.afrovibes.nl",
    organizerBio: "Afrovibes is de grootste Afrikaanse culturele organisatie in Nederland.",
  },
  {
    title: "Amapiano Night – Club Shelter Amsterdam",
    description: `De snelst groeiende muziekstijl uit Zuid-Afrika heeft Amsterdam bereikt. Club Shelter organiseert een speciale Amapiano nacht met DJ's rechtstreeks uit Johannesburg, gecombineerd met de beste Amsterdam-gebaseerde Afrikaanse DJs.\n\nGuest DJ's: Uncle Waffles (ZA), Kabza de Small (ZA)\nLocal support: DJ Nomad, Afro Brothers NL\n\n🎟️ TICKETS: €18 via shelteramsterdam.nl. 21+ only.`,
    date: new Date("2026-05-09T23:00:00"),
    endDate: new Date("2026-05-10T07:00:00"),
    location: "Shelter Amsterdam, Amsterdam-Noord",
    city: "Amsterdam",
    category: "nightlife",
    subcategory: "afrobeats",
    musicGenre: "afrobeats",
    isPaid: true,
    price: 18,
    priceModel: "paid",
    adultPrice: 18,
    image: "https://images.unsplash.com/photo-1502691876148-a84978e59af8?w=800&q=80",
    tags: ["amapiano", "afrobeats", "club", "amsterdam", "zuidafrika"],
    vibeLabels: ["Energetic", "Urban"],
    moodTags: ["energetic", "urban"],
    capacity: 700,
    attendeeCount: 650,
    likeCount: 890,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: false,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.shelteramsterdam.nl",
    organizerBio: "Shelter Amsterdam – Thuis voor underground clubmuziek.",
  },

  // REGGAE
  {
    title: "Reggae Weekend Amsterdam – Bob Marley Tribute",
    description: `Een weekend vol reggae, dancehall en ska ter ere van de erfenis van Bob Marley. Met livebands, DJ sets, Jamaicaans eten, handgemaakte kunst en een relaxte, positieve sfeer voor iedereen.\n\nMaandag 6 februari – Bob Marley's verjaardag tribute\n\nBands: The Wailers NL, Jah Division, Amsterdam Ska Orchestra\n\n🌿 ROOTS & CULTURE – Voor de hele familie\n🎟️ TICKETS: €18 via Paradiso. Kinderen onder 12 gratis`,
    date: new Date("2026-08-08T14:00:00"),
    endDate: new Date("2026-08-09T23:00:00"),
    location: "Paradiso Amsterdam",
    city: "Amsterdam",
    category: "festival",
    subcategory: "reggae",
    musicGenre: "reggae",
    isPaid: true,
    price: 18,
    priceModel: "from",
    adultPrice: 18,
    kidsPrice: 0,
    image: "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=800&q=80",
    tags: ["reggae", "dancehall", "ska", "bob-marley", "roots"],
    vibeLabels: ["Chill", "Family"],
    moodTags: ["chill", "family"],
    capacity: 1200,
    attendeeCount: 900,
    likeCount: 670,
    kidFriendly: true,
    familyFriendly: true,
    isIndoor: true,
    crowdLevel: "medium",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.paradiso.nl",
    organizerBio: "Reggae Weekend Amsterdam is de grootste reggae viering van Nederland.",
  },

  // LATIN
  {
    title: "Salsa Festival Den Haag – Congresgebouw",
    description: `Het Den Haag Salsa Festival is hét grootste Latijns-Amerikaans dansfestival van Nederland. Met workshops, social dancing, live bands en shows van internationaal gerenommeerde salsa dansers en muzikanten.\n\nWorkshops: Cuban Salsa, On2 Salsa, Bachata, Kizomba, Reggaeton\nLive bands: La Sonora de Ricardo, Mayito Rivera y su Orquesta\nDJ's: DJ Salsa NL, DJ Mambo Mike\n\n🎟️ TICKETS: Weekend pas €65, dag €30 via salsafestivaldenhaag.nl`,
    date: new Date("2026-05-22T17:00:00"),
    endDate: new Date("2026-05-24T04:00:00"),
    location: "Congresgebouw, Den Haag",
    city: "Den Haag",
    category: "dance",
    subcategory: "latin",
    musicGenre: "latin",
    isPaid: true,
    price: 30,
    priceModel: "from",
    adultPrice: 30,
    image: "https://images.unsplash.com/photo-1545959570-a94084071b5d?w=800&q=80",
    tags: ["salsa", "latin", "dans", "workshop", "bachata"],
    vibeLabels: ["Energetic", "Luxury"],
    moodTags: ["energetic", "luxury"],
    capacity: 3000,
    attendeeCount: 2600,
    likeCount: 1240,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: true,
    isTrending: false,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.salsafestivaldenhaag.nl",
    organizerBio: "Den Haag Salsa Festival is al 15 jaar het grootste Latijns-Amerikaanse dansevenement van Nederland.",
  },
  {
    title: "Bachata Gratis Workshop – Utrecht Social Dancing",
    description: `Iedere maandagavond organiseert de Latin Dance Club Utrecht een gratis bachata workshop voor beginners, gevolgd door social dancing voor alle levels. Perfect voor wie de Latijnse danscultuur wil leren kennen!\n\nProgramma:\n20:00 - Gratis beginners workshop (1 uur)\n21:00 - Social dancing voor iedereen\n23:00 - Afsluiting\n\n🆓 GRATIS WORKSHOP – Social dancing €5 bijdrage`,
    date: new Date("2026-04-06T20:00:00"),
    endDate: new Date("2026-04-06T23:00:00"),
    location: "Leidsche Rijn Centrum, Utrecht",
    city: "Utrecht",
    category: "dance",
    subcategory: "latin",
    musicGenre: "latin",
    isPaid: false,
    price: 0,
    priceModel: "free",
    image: "https://images.unsplash.com/photo-1518611507436-f9221403cca2?w=800&q=80",
    tags: ["bachata", "salsa", "workshop", "gratis", "social-dancing"],
    vibeLabels: ["Chill", "Energetic"],
    moodTags: ["chill", "energetic"],
    capacity: 80,
    attendeeCount: 60,
    likeCount: 89,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "medium",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: false,
    externalTicketLink: null as any,
    organizerBio: "Latin Dance Club Utrecht organiseert wekelijkse dansworkshops.",
  },

  // POP
  {
    title: "Appelsap Festival 2026 – Flevopark Amsterdam",
    description: `Appelsap Festival, Amsterdams oudste en meest geliefde urban outdoor festival, keert terug naar het Flevopark. Gratis toegankelijk en met een lineup van de beste Nederlandse en internationale urban muziek: hip-hop, neo-soul, funk, R&B en meer.\n\nLineup TBA – altijd een mix van gevestigde namen en opkomend talent.\n\nActiviteiten: Live art, breakdance, sporttoernooien, foodtrucks\n\n🆓 GRATIS – Geen tickets nodig`,
    date: new Date("2026-08-15T12:00:00"),
    endDate: new Date("2026-08-15T22:00:00"),
    location: "Flevopark, Amsterdam-Oost",
    city: "Amsterdam",
    category: "festival",
    subcategory: "pop",
    musicGenre: "pop",
    isPaid: false,
    price: 0,
    priceModel: "free",
    image: "https://images.unsplash.com/photo-1501386761578-eaa54b4e75a8?w=800&q=80",
    tags: ["gratis", "festival", "urban", "pop", "appelsap"],
    vibeLabels: ["Family", "Energetic"],
    moodTags: ["family", "energetic"],
    capacity: 20000,
    attendeeCount: 15000,
    likeCount: 8900,
    kidFriendly: true,
    familyFriendly: true,
    isIndoor: false,
    crowdLevel: "busy",
    isFeatured: true,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.appelsap.net",
    organizerBio: "Appelsap Festival is Amsterdams oudste gratis urban outdoor festival.",
  },
  {
    title: "Pitch Festival 2026 – Westerpark Amsterdam",
    description: `Pitch Festival vindt plaats in het Westerpark van Amsterdam en brengt een mix van Nederlandse en internationale popacts, singer-songwriters en indie-acts. Klein, intiem en stijlvol.\n\nLineup: Still Woozy, Phoebe Bridgers, Lianne La Havas, Jungle.\n\n🎟️ TICKETS: €39 dag / €69 weekend via pitchfestival.nl`,
    date: new Date("2026-08-22T13:00:00"),
    endDate: new Date("2026-08-23T23:00:00"),
    location: "Westerpark, Amsterdam",
    city: "Amsterdam",
    category: "festival",
    subcategory: "pop",
    musicGenre: "pop",
    isPaid: true,
    price: 39,
    priceModel: "from",
    adultPrice: 39,
    image: "https://images.unsplash.com/photo-1501386761578-eaa54b4e75a8?w=800&q=80",
    tags: ["pop", "indie", "festival", "westerpark", "singer-songwriter"],
    vibeLabels: ["Chill", "Creative"],
    moodTags: ["chill", "creative"],
    capacity: 8000,
    attendeeCount: 7200,
    likeCount: 3400,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: false,
    crowdLevel: "busy",
    isFeatured: true,
    isTrending: false,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.pitchfestival.nl",
    organizerBio: "Pitch Festival is een intiem popmuziek festival in Amsterdam.",
  },

  // CLASSICAL
  {
    title: "Concertgebouw – Gratis Lunchconcert Amsterdam",
    description: `Het Concertgebouw opent iedere woensdag zijn deuren voor een gratis lunchconcert. Jonge, getalenteerde musici van het Conservatorium en internationaal gerenommeerde solisten treden op in de intieme Recitalzaal.\n\nProgramma varieert: strijkkwartetten, pianosolo, liedkunst, kamermuziek.\n\n🆓 GRATIS – Deuren open 12:15, concert 12:30-13:30\n📍 Recitalzaal – Beperkte plaatsen, wees er op tijd bij!`,
    date: new Date("2026-04-08T12:15:00"),
    endDate: new Date("2026-04-08T13:30:00"),
    location: "Concertgebouw Amsterdam, Concertgebouwplein 10",
    city: "Amsterdam",
    category: "music",
    subcategory: "classical",
    musicGenre: "classical",
    isPaid: false,
    price: 0,
    priceModel: "free",
    image: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&q=80",
    tags: ["klassiek", "lunchconcert", "gratis", "concertgebouw", "kamermuziek"],
    vibeLabels: ["Luxury", "Chill"],
    moodTags: ["luxury", "chill"],
    capacity: 150,
    attendeeCount: 100,
    likeCount: 230,
    kidFriendly: true,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "medium",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.concertgebouw.nl/lunchconcerts",
    organizerBio: "Het Concertgebouw is het meest gerenommeerde concertzaal ter wereld.",
  },
  {
    title: "Danstheater AGA ZIV – Spoken Word & Soul, Utrecht",
    description: `Danstheater AGA ZIV presenteert een avond vol spoken word, urban poetry en live soul muziek. Dichters, muzikanten en performers van divers pluimage komen samen voor een intieme en krachtige avond.\n\nVanaf 20:30 open mic voor aanmeldingen (max 5 min per act)\nHeadliner: Lisette Lombé (BE) – gelauwerd spoken word kunstenaar\n\n🎟️ TICKETS: €12 via de website`,
    date: new Date("2026-06-05T19:30:00"),
    endDate: new Date("2026-06-05T22:30:00"),
    location: "Danstheater AGA ZIV, Utrecht",
    city: "Utrecht",
    category: "cultural",
    subcategory: "classical",
    musicGenre: "classical",
    isPaid: true,
    price: 12,
    priceModel: "paid",
    adultPrice: 12,
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&q=80",
    tags: ["spoken-word", "poetry", "soul", "theater", "diversiteit"],
    vibeLabels: ["Creative", "Chill"],
    moodTags: ["creative", "chill"],
    capacity: 120,
    attendeeCount: 90,
    likeCount: 145,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "medium",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.danstheateraga.nl",
    organizerBio: "Danstheater AGA ZIV is een cultuurhuis voor urban arts in Utrecht.",
  },

  // DANCE / WORLD
  {
    title: "Mystery Land 2026 – Electronisch Muziekfestival, Haarlemmermeer",
    description: `Mysteryland is het oudste dance festival ter wereld en keert terug naar het festivalterrein in de Haarlemmermeer. Met meer dan 20 stages brengt het festival house, techno, hardstyle, drum & bass, trance en experimental sounds samen.\n\nMeer dan 200 acts over 3 dagen. Camping beschikbaar.\n\n🎟️ TICKETS: Dag €75, weekend €160, camping €30 extra. Via mysteryland.com`,
    date: new Date("2026-08-28T14:00:00"),
    endDate: new Date("2026-08-31T07:00:00"),
    location: "Haarlemmermeer, Noord-Holland",
    city: "Haarlem",
    category: "festival",
    subcategory: "electronic",
    musicGenre: "electronic",
    isPaid: true,
    price: 75,
    priceModel: "from",
    adultPrice: 75,
    image: "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&q=80",
    tags: ["electronic", "house", "techno", "hardstyle", "festival", "camping"],
    vibeLabels: ["Energetic", "Urban"],
    moodTags: ["energetic", "urban"],
    capacity: 60000,
    attendeeCount: 55000,
    likeCount: 18000,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: false,
    crowdLevel: "busy",
    isFeatured: true,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.mysteryland.com",
    organizerBio: "Mysteryland is het oudste dance festival ter wereld, opgericht in 1993.",
  },
  {
    title: "World Music Festival – Oosterpark Amsterdam",
    description: `Het World Music Festival in het Oosterpark is een jaarlijkse gratis viering van de muzikale diversiteit van Amsterdam. Van Caraïbische ritmes tot Oost-Afrikaanse drumming, van flamenco tot gamelan – een echte wereldreis.\n\nArtiesten uit meer dan 20 landen\nKinderworkshops: 11:00-14:00\nFood village met gerechten uit alle windstreken\n\n🆓 GRATIS – Voor iedereen`,
    date: new Date("2026-06-13T11:00:00"),
    endDate: new Date("2026-06-13T21:00:00"),
    location: "Oosterpark, Amsterdam",
    city: "Amsterdam",
    category: "festival",
    subcategory: "world",
    musicGenre: "world",
    isPaid: false,
    price: 0,
    priceModel: "free",
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80",
    tags: ["world-music", "gratis", "multicultureel", "oosterpark", "diversiteit"],
    vibeLabels: ["Family", "Creative"],
    moodTags: ["family", "creative"],
    capacity: 10000,
    attendeeCount: 6000,
    likeCount: 2100,
    kidFriendly: true,
    familyFriendly: true,
    isIndoor: false,
    crowdLevel: "busy",
    isFeatured: false,
    isTrending: false,
    isVerifiedOrganizer: true,
    externalTicketLink: null as any,
    organizerBio: "World Music Festival Amsterdam brengt muzikale diversiteit tot leven.",
  },

  // ROCK
  {
    title: "Lowlands 2026 – Rock & Alternative",
    description: `Lowlands Festival keert terug naar Biddinghuizen met de beste rock- en alternativebands van Nederland en internationaal. Een van de grootste muziekfestivals van Nederland met meerdere podia, kunst en cultuur.\n\nArtistenlineup: Pearl Jam, Arctic Monkeys, The National, Wolf Alice, Interpol, Fontaines D.C., IDLES.\n\n🎟️ TICKETS: Weekend €235, dag €85 via lowlands.com`,
    date: new Date("2026-08-21T12:00:00"),
    endDate: new Date("2026-08-23T23:00:00"),
    location: "Walibi Holland, Biddinghuizen",
    city: "Biddinghuizen",
    category: "festival",
    subcategory: "rock",
    musicGenre: "rock",
    isPaid: true,
    price: 235,
    priceModel: "from",
    adultPrice: 235,
    image: "https://images.unsplash.com/photo-1540747913346-19378d0db66c?w=800&q=80",
    tags: ["rock", "alternatief", "festival", "lowlands", "indie"],
    vibeLabels: ["Energetic", "Creative"],
    moodTags: ["energetic", "creative"],
    capacity: 55000,
    attendeeCount: 50000,
    likeCount: 15000,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: false,
    crowdLevel: "busy",
    isFeatured: true,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.lowlands.nl/tickets",
    organizerBio: "Lowlands is het grootste indie- en rockfestival van Nederland.",
  },
  {
    title: "Into the Great Wide Open 2026 – Vlieland Rock",
    description: `Into the Great Wide Open is een uniek muziekfestival op het eiland Vlieland. Drie dagen lang rock, indie en alternatieve muziek in een adembenemende omgeving, zonder auto's en gedoe.\n\nLineup: Dua Lipa, Editors, Nick Cave & The Bad Seeds, Kae Tempest, Nieve Ella, Personal Trainer.\n\n⛴️ Per veerboot bereikbaar\n🎟️ TICKETS: €199 incl. overvaart via itgwo.nl`,
    date: new Date("2026-09-02T14:00:00"),
    endDate: new Date("2026-09-04T23:00:00"),
    location: "Vlieland, Waddeneilanden",
    city: "Vlieland",
    category: "festival",
    subcategory: "rock",
    musicGenre: "rock",
    isPaid: true,
    price: 199,
    priceModel: "from",
    adultPrice: 199,
    image: "https://images.unsplash.com/photo-1501612780327-45045538702b?w=800&q=80",
    tags: ["rock", "indie", "eiland", "vlieland", "festival"],
    vibeLabels: ["Chill", "Creative"],
    moodTags: ["chill", "creative"],
    capacity: 8000,
    attendeeCount: 7500,
    likeCount: 3200,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: false,
    crowdLevel: "medium",
    isFeatured: false,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.itgwo.nl/tickets",
    organizerBio: "Into the Great Wide Open brengt muziek naar het prachtige Vlieland.",
  },

  // DANCE (genre: dance — distinct from dance category)
  {
    title: "Dutch Open Streetdance Championships 2026 – Rotterdam",
    description: `De Dutch Open Streetdance Championships is de grootste open straatdans competitie van Nederland. Crews en soloartiesten uit het hele land strijden om de nationale titel in breaking, popping, locking, house en urban choreography.\n\nDivisies: Kids (8-12), Juniors (13-17), Adults (18+)\nBattleformaten: 1-on-1 en crew (5-8 personen)\n\n🎟️ TICKETS: Toeschouwers €15, deelname €25-€45 per persoon via dutchopen.nl`,
    date: new Date("2026-05-09T10:00:00"),
    endDate: new Date("2026-05-09T22:00:00"),
    location: "Ahoy Rotterdam, Rotterdam",
    city: "Rotterdam",
    category: "dance",
    subcategory: "streetdance",
    musicGenre: "dance",
    isPaid: true,
    price: 15,
    priceModel: "from",
    adultPrice: 15,
    image: "https://images.unsplash.com/photo-1547153760-18fc86324498?w=800&q=80",
    tags: ["streetdance", "breaking", "popping", "locking", "urban", "competitie"],
    vibeLabels: ["Energetic", "Urban"],
    moodTags: ["energetic", "urban"],
    capacity: 3000,
    attendeeCount: 2500,
    likeCount: 980,
    kidFriendly: true,
    familyFriendly: true,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: false,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.dutchopenstancechamps.nl/tickets",
    organizerBio: "Dutch Open Streetdance Championships is de grootste nationale streetdance competitie.",
  },
  {
    title: "House Dance International – Amsterdam Edition 2026",
    description: `House Dance International Amsterdam Edition brengt de beste house dancers uit Europa samen voor een epische dag vol battles, workshops en performances. Van Underground Club House tot Waacking en Vogue.\n\nWorkshops: Chicago Footwork, Vogue Fem, Waacking, Club House\nBattles: 2-on-2 House, 1-on-1 Vogue, Waacking Open\n\n🎟️ TICKETS: Dagpas €20, battle entry €30 via housedanceinternational.com`,
    date: new Date("2026-07-18T12:00:00"),
    endDate: new Date("2026-07-18T23:59:00"),
    location: "Melkweg, Amsterdam",
    city: "Amsterdam",
    category: "dance",
    subcategory: "house",
    musicGenre: "dance",
    isPaid: true,
    price: 20,
    priceModel: "from",
    adultPrice: 20,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80",
    tags: ["house", "dance", "vogue", "waacking", "battle", "workshop"],
    vibeLabels: ["Energetic", "Creative"],
    moodTags: ["energetic", "creative"],
    capacity: 800,
    attendeeCount: 650,
    likeCount: 410,
    kidFriendly: false,
    familyFriendly: false,
    isIndoor: true,
    crowdLevel: "busy",
    isFeatured: false,
    isTrending: true,
    isVerifiedOrganizer: true,
    externalTicketLink: "https://www.housedanceinternational.com/amsterdam",
    organizerBio: "House Dance International is de toonaangevende organisatie voor house dance events in Europa.",
  },
];

export async function seedDutchEvents() {
  // Fast-path: check total event count with a single COUNT query.
  // If the DB already has most of the seeded events, skip all 59 findFirst queries.
  try {
    const { sql: sqlTag } = await import("drizzle-orm");
    const countResult = await db.execute(sqlTag`SELECT COUNT(*)::int AS cnt FROM events`);
    const existingCount = (countResult.rows[0] as any)?.cnt ?? 0;
    if (existingCount >= dutchEvents.length - 5) {
      console.log(`🌷 Skipping seed — ${existingCount} events already in DB (need ${dutchEvents.length})`);
      return;
    }
    console.log(`🌷 Seeding ${dutchEvents.length} Dutch urban culture events (found ${existingCount} existing)...`);
  } catch (err: any) {
    console.log(`🌷 Could not count events (${err.message}), proceeding with full seed check...`);
  }

  // Resolve organizer ID dynamically — find the first admin user by known emails
  // (user IDs differ between dev and production databases)
  let organizerId: number | null = null;
  try {
    const { or, eq } = await import("drizzle-orm");
    const adminUser = await db.query.users.findFirst({
      where: (u) => or(
        eq(u.email, "riki@dancehealthy.net"),
        eq(u.email, "rmaru2889@gmail.com"),
        eq(u.email, "oudaialmouti@gmail.com")
      ),
    });
    if (adminUser) {
      organizerId = adminUser.id;
      console.log(`🌷 Using organizer ID ${organizerId} (${adminUser.email})`);
    } else {
      console.log(`🌷 No admin user found — seeding with null organizer`);
    }
  } catch (_) {}

  let inserted = 0;
  let skipped = 0;
  let updated = 0;

  for (const evt of dutchEvents) {
    try {
      const existing = await db.query.events.findFirst({
        where: (e, { eq }) => eq(e.title, evt.title),
      });

      if (existing) {
        // Backfill musicGenre and source on existing events if missing
        const needsUpdate = !existing.musicGenre && (evt as any).musicGenre;
        if (needsUpdate) {
          const { sql } = await import("drizzle-orm");
          await db.execute(
            sql`UPDATE events SET music_genre = ${(evt as any).musicGenre}, source = ${(evt as any).source || "manual"} WHERE id = ${existing.id}`
          );
          updated++;
        }
        skipped++;
        continue;
      }

      await db.insert(events).values({
        title: evt.title,
        description: evt.description,
        date: evt.date,
        endDate: evt.endDate,
        location: evt.location,
        city: evt.city,
        category: evt.category,
        subcategory: evt.subcategory,
        isPaid: evt.isPaid,
        price: evt.price,
        priceModel: evt.priceModel,
        adultPrice: evt.adultPrice,
        kidsPrice: (evt as any).kidsPrice,
        familyPrice: (evt as any).familyPrice,
        image: evt.image,
        gallery: evt.gallery ?? [],
        tags: evt.tags,
        vibeLabels: evt.vibeLabels,
        moodTags: evt.moodTags,
        capacity: evt.capacity,
        attendeeCount: evt.attendeeCount,
        likeCount: evt.likeCount,
        kidFriendly: evt.kidFriendly,
        familyFriendly: evt.familyFriendly,
        isIndoor: evt.isIndoor,
        crowdLevel: evt.crowdLevel,
        isFeatured: evt.isFeatured,
        isTrending: evt.isTrending,
        isVerifiedOrganizer: evt.isVerifiedOrganizer,
        externalTicketLink: evt.externalTicketLink,
        organizerBio: evt.organizerBio,
        musicGenre: (evt as any).musicGenre,
        source: (evt as any).source || "manual",
        organizerId: organizerId,
        status: "approved",
      });
      inserted++;
    } catch (err: any) {
      console.error(`Failed to insert "${evt.title}":`, err.message);
    }
  }

  // Ensure all seeded events are approved
  try {
    const { sql } = await import("drizzle-orm");
    if (organizerId) {
      await db.execute(
        sql`UPDATE events SET status = 'approved' WHERE organizer_id = ${organizerId} AND status = 'pending'`
      );
    }
  } catch (_) {}

  console.log(`✅ Done: ${inserted} inserted, ${skipped} skipped, ${updated} genre-backfilled`);
}
