import Stripe from "stripe";
import { getUncachableStripeClient } from "./stripeClient";

// Set a flag to track if Stripe is properly configured
let isStripeConfigured = false;

// Initialize stripe function that uses Replit connection
async function getStripeClient(): Promise<Stripe | null> {
  try {
    const stripe = await getUncachableStripeClient();
    isStripeConfigured = true;
    return stripe;
  } catch (error) {
    console.error("Failed to get Stripe client:", error);
    isStripeConfigured = false;
    return null;
  }
}

// We'll create these prices dynamically if they don't exist
// The IDs will be generated by Stripe but we'll store them for reuse
export const SUBSCRIPTION_PRICES = {
  PREMIUM_MONTHLY: process.env.STRIPE_PREMIUM_MONTHLY_PRICE_ID || "", 
  PREMIUM_YEARLY: process.env.STRIPE_PREMIUM_YEARLY_PRICE_ID || "",
};

// Subscription tier details for easy reference
export const SUBSCRIPTION_TIERS = {
  FREE: {
    name: "Free",
    features: [
      "Basic location browsing",
      "View community events",
      "Limited number of map filters",
      "Standard service booking"
    ],
    price: 0,
  },
  PREMIUM: {
    name: "Premium",
    features: [
      "Unlimited location browsing",
      "Advanced map filtering options",
      "Early access to events",
      "Discounted event tickets",
      "Priority booking for services",
      "No booking fees",
      "Create unlimited locations"
    ],
    monthlyPrice: 10.00,
    yearlyPrice: 90.00,
  }
};

export async function createPaymentIntent(options: {
  amount: number;
  currency?: string;
  description?: string;
  metadata?: { [key: string]: string };
  idempotencyKey?: string;
}) {
  const stripe = await getStripeClient();
  if (!stripe) {
    console.error("Stripe is not configured. Please provide a valid Stripe connection.");
    throw new Error("Stripe is not configured. Please provide a valid Stripe connection.");
  }
  
  if (!options.amount || options.amount <= 0) {
    console.error("Invalid payment amount:", options.amount);
    throw new Error(`Invalid payment amount: ${options.amount}. Amount must be a positive number.`);
  }
  
  console.log("Creating payment intent with amount:", options.amount, "cents");
  
  // Generate a stable idempotency key if not provided — prevents duplicate charges
  // on network retries. Key encodes amount + currency + timestamp bucket (1-minute window).
  const idempotencyKey = options.idempotencyKey ||
    `pi_${options.amount}_${(options.currency || "eur")}_${Math.floor(Date.now() / 60000)}`;

  try {
    const paymentIntent = await stripe.paymentIntents.create({
      amount: options.amount,
      currency: options.currency || "eur",
      description: options.description,
      metadata: options.metadata || {},
      payment_method_types: ['card', 'ideal'],
    }, {
      idempotencyKey,
    });

    // Verify the payment intent was created successfully with a client secret
    if (!paymentIntent.client_secret) {
      console.error("Payment intent created but missing client_secret", paymentIntent.id);
      throw new Error("Payment intent created but missing client secret");
    }
    
    console.log(`Payment intent ${paymentIntent.id} created successfully`);
    
    return paymentIntent;
  } catch (error: any) {
    console.error("Error creating payment intent:", error);
    throw new Error(`Stripe error: ${error.message}`);
  }
}

export async function createRefund(paymentIntentId: string) {
  const stripe = await getStripeClient();
  if (!stripe) {
    throw new Error("Stripe is not configured. Please provide a valid Stripe connection.");
  }
  
  try {
    const refund = await stripe.refunds.create({
      payment_intent: paymentIntentId,
    });

    return refund;
  } catch (error: any) {
    throw new Error(error.message);
  }
}

export async function createCustomer(email: string, name?: string) {
  const stripe = await getStripeClient();
  if (!stripe) {
    throw new Error("Stripe is not configured. Please provide a valid Stripe connection.");
  }
  
  try {
    const customer = await stripe.customers.create({
      email,
      name,
    });
    return customer;
  } catch (error: any) {
    throw new Error(`Failed to create Stripe customer: ${error.message}`);
  }
}

export async function createSubscription(options: {
  customerId: string;
  priceId: string;
  metadata?: { [key: string]: string };
}) {
  const stripe = await getStripeClient();
  if (!stripe) {
    throw new Error("Stripe is not configured. Please provide a valid Stripe connection.");
  }
  
  try {
    const subscription = await stripe.subscriptions.create({
      customer: options.customerId,
      items: [{ price: options.priceId }],
      payment_behavior: 'default_incomplete',
      expand: ['latest_invoice.payment_intent'],
      metadata: options.metadata,
    });
    
    return subscription;
  } catch (error: any) {
    throw new Error(`Failed to create subscription: ${error.message}`);
  }
}

export async function cancelSubscription(subscriptionId: string) {
  const stripe = await getStripeClient();
  if (!stripe) {
    throw new Error("Stripe is not configured. Please provide a valid Stripe connection.");
  }
  
  try {
    const subscription = await stripe.subscriptions.cancel(subscriptionId);
    return subscription;
  } catch (error: any) {
    throw new Error(`Failed to cancel subscription: ${error.message}`);
  }
}

export async function updateSubscription(subscriptionId: string, priceId: string) {
  const stripe = await getStripeClient();
  if (!stripe) {
    throw new Error("Stripe is not configured. Please provide a valid Stripe connection.");
  }
  
  try {
    const subscription = await stripe.subscriptions.retrieve(subscriptionId);
    
    if (!subscription || !subscription.items.data[0]?.id) {
      throw new Error("Invalid subscription");
    }
    
    const updatedSubscription = await stripe.subscriptions.update(
      subscriptionId,
      {
        items: [{
          id: subscription.items.data[0].id,
          price: priceId,
        }],
      }
    );
    
    return updatedSubscription;
  } catch (error: any) {
    throw new Error(`Failed to update subscription: ${error.message}`);
  }
}

export async function handleWebhook(
  signature: string,
  payload: Buffer,
  endpointSecret: string
) {
  const stripe = await getStripeClient();
  if (!stripe) {
    throw new Error("Stripe is not configured. Please provide a valid Stripe connection.");
  }
  
  try {
    const event = stripe.webhooks.constructEvent(
      payload,
      signature,
      endpointSecret
    );

    return event;
  } catch (error: any) {
    throw new Error(error.message);
  }
}

/**
 * Retrieves a payment intent by ID and returns its current status
 * @param paymentIntentId The ID of the payment intent to retrieve
 * @param expand Whether to expand the payment intent to include additional data
 * @returns The payment intent object
 */
export async function getPaymentIntentStatus(paymentIntentId: string, expand: boolean = false) {
  const stripe = await getStripeClient();
  if (!stripe) {
    throw new Error("Stripe is not configured. Please provide a valid Stripe connection.");
  }
  
  console.log(`Retrieving payment intent status for ${paymentIntentId} ${expand ? 'with expanded data' : ''}`);
  
  try {
    // Set up retrieval options
    const retrieveOptions: Stripe.PaymentIntentRetrieveParams = {};
    
    // If expanded data is requested, include related objects
    if (expand) {
      retrieveOptions.expand = [
        'payment_method',
        'latest_charge',
        'customer'
      ];
    }
    
    // Retrieve the payment intent with optional expanded data
    const paymentIntent = await stripe.paymentIntents.retrieve(
      paymentIntentId, 
      retrieveOptions
    );
    
    console.log(`Retrieved payment intent status: ${paymentIntent.status} for ${paymentIntentId}`);
    
    return {
      id: paymentIntent.id,
      status: paymentIntent.status,
      amount: paymentIntent.amount,
      currency: paymentIntent.currency,
      created: paymentIntent.created,
      metadata: paymentIntent.metadata,
      payment_method_types: paymentIntent.payment_method_types,
      payment_method: paymentIntent.payment_method,
      latest_charge: paymentIntent.latest_charge,
      customer: paymentIntent.customer,
      description: paymentIntent.description,
      next_action: paymentIntent.next_action
    };
  } catch (error: any) {
    console.error(`Error retrieving payment intent status for ${paymentIntentId}:`, error.message);
    throw new Error(`Failed to retrieve payment intent: ${error.message}`);
  }
}

// Helper function to create products and prices for our subscription plans
export async function initializeStripePrices() {
  const stripe = await getStripeClient();
  if (!stripe) {
    console.warn("Stripe is not configured. Skipping price initialization.");
    return {
      monthlyPriceId: "",
      yearlyPriceId: ""
    };
  }
  
  console.log("Initializing Stripe products and prices...");
  
  try {
    // Create or retrieve the premium product
    let premiumProduct;
    const existingProducts = await stripe.products.list({ limit: 100 });
    
    const existingPremiumProduct = existingProducts.data.find(p => 
      p.name === "Urban Culture Premium" && p.active
    );
    
    if (existingPremiumProduct) {
      console.log("Found existing premium product:", existingPremiumProduct.id);
      premiumProduct = existingPremiumProduct;
    } else {
      console.log("Creating new premium product...");
      premiumProduct = await stripe.products.create({
        name: "Urban Culture Premium",
        description: "Premium membership for Urban Culture platform",
        active: true,
      });
      console.log("Created new premium product:", premiumProduct.id);
    }
    
    // Create or retrieve the premium monthly price
    let monthlyPrice;
    const existingPrices = await stripe.prices.list({ 
      product: premiumProduct.id,
      limit: 100 
    });
    
    const existingMonthlyPrice = existingPrices.data.find(p => 
      p.nickname === "Monthly" && 
      p.unit_amount === Math.round(SUBSCRIPTION_TIERS.PREMIUM.monthlyPrice * 100) &&
      p.recurring?.interval === "month"
    );
    
    if (existingMonthlyPrice) {
      console.log("Found existing monthly price:", existingMonthlyPrice.id);
      monthlyPrice = existingMonthlyPrice;
      SUBSCRIPTION_PRICES.PREMIUM_MONTHLY = existingMonthlyPrice.id;
    } else {
      console.log("Creating new monthly price...");
      monthlyPrice = await stripe.prices.create({
        product: premiumProduct.id,
        nickname: "Monthly",
        unit_amount: Math.round(SUBSCRIPTION_TIERS.PREMIUM.monthlyPrice * 100),
        currency: "eur",
        recurring: {
          interval: "month",
        },
      });
      console.log("Created new monthly price:", monthlyPrice.id);
      SUBSCRIPTION_PRICES.PREMIUM_MONTHLY = monthlyPrice.id;
    }
    
    // Create or retrieve the premium yearly price
    let yearlyPrice;
    const existingYearlyPrice = existingPrices.data.find(p => 
      p.nickname === "Yearly" && 
      p.unit_amount === Math.round(SUBSCRIPTION_TIERS.PREMIUM.yearlyPrice * 100) &&
      p.recurring?.interval === "year"
    );
    
    if (existingYearlyPrice) {
      console.log("Found existing yearly price:", existingYearlyPrice.id);
      yearlyPrice = existingYearlyPrice;
      SUBSCRIPTION_PRICES.PREMIUM_YEARLY = existingYearlyPrice.id;
    } else {
      console.log("Creating new yearly price...");
      yearlyPrice = await stripe.prices.create({
        product: premiumProduct.id,
        nickname: "Yearly",
        unit_amount: Math.round(SUBSCRIPTION_TIERS.PREMIUM.yearlyPrice * 100),
        currency: "eur",
        recurring: {
          interval: "year",
        },
      });
      console.log("Created new yearly price:", yearlyPrice.id);
      SUBSCRIPTION_PRICES.PREMIUM_YEARLY = yearlyPrice.id;
    }
    
    console.log("Stripe prices initialized:");
    console.log("Monthly Price ID:", SUBSCRIPTION_PRICES.PREMIUM_MONTHLY);
    console.log("Yearly Price ID:", SUBSCRIPTION_PRICES.PREMIUM_YEARLY);
    
    return {
      monthlyPriceId: SUBSCRIPTION_PRICES.PREMIUM_MONTHLY,
      yearlyPriceId: SUBSCRIPTION_PRICES.PREMIUM_YEARLY
    };
  } catch (error: any) {
    console.error("Error initializing Stripe prices:", error.message);
    throw new Error(`Failed to initialize Stripe prices: ${error.message}`);
  }
}