/**
 * restore-users.ts
 *
 * One-time migration: upserts the 11 exported users into the production
 * Neon/PostgreSQL database so they can sign in via Firebase again.
 *
 * Usage (run from project root with Railway DB URL in env):
 *   $Env:DATABASE_URL="postgresql://..."   # PowerShell
 *   npx tsx scripts/restore-users.ts
 *
 * Safe to run multiple times — uses ON CONFLICT DO UPDATE (upsert).
 * Does NOT delete any other data.
 */

import { drizzle } from "drizzle-orm/neon-http";
import { neon } from "@neondatabase/serverless";
import { users } from "../shared/schema";
import { sql } from "drizzle-orm";

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) {
  console.error("❌  DATABASE_URL environment variable is not set.");
  process.exit(1);
}

// ── Exported users (raw DB export from old database) ─────────────────────────
const USERS = [
  {
    id: 3,
    email: "oudaialmouti@gmail.com",
    password: "$2b$10$HYICSPUv9Ol9HsIhslyz2.HimHDN/zVjXCudHMfScemJQcbz/crX6",
    display_name: "Riki Almouti",
    role: "admin",
    bio: "Love to break",
    profile_picture: "https://res.cloudinary.com/dbutuy5tt/image/upload/v1764516011/profiles/sfmjyyvrmavwmcbpybt6.jpg",
    art_type: "",
    organization_name: "",
    kvk_number: "",
    btw_number: "",
    kvk_verification_status: "pending",
    kvk_verified_at: null,
    kvk_verification_fail_reason: null,
    is_verified: true,
    is_approved: true,
    location: "Zaandam, Netherlands",
    stripe_customer_id: null,
    status: "active",
    tos_accepted: false,
    tos_accepted_at: null,
    tos_version: null,
    created_at: "2025-11-24T15:28:38.084Z",
    updated_at: "2025-11-30T15:20:37.578Z",
    firebase_uid: "rqi8wTPN4fRfLh3QoDvkg7f3xSL2",
    is_hidden_in_community: false,
    home_street: null,
    home_postcode: null,
    home_city: null,
    home_country: null,
    is_ai_premium: false,
    can_add_spots: false,
    can_create_polls: false,
    can_share_content: false,
  },
  {
    id: 4,
    email: "rmaru2889@gmail.com",
    password: "$2b$10$5efmYvqVPS2a8RODVJwz3uHcbwXwPmAkZ89Gba3fEcslyWMuTGU9y",
    display_name: "riki",
    role: "admin",
    bio: "",
    profile_picture: "https://res.cloudinary.com/dbutuy5tt/image/upload/v1764030336/profiles/piguumavjt1u0nb3qyay.png",
    art_type: "",
    organization_name: "",
    kvk_number: "",
    btw_number: "",
    kvk_verification_status: "pending",
    kvk_verified_at: null,
    kvk_verification_fail_reason: null,
    is_verified: true,
    is_approved: true,
    location: "Zaandam, Netherlands",
    stripe_customer_id: null,
    status: "active",
    tos_accepted: false,
    tos_accepted_at: null,
    tos_version: null,
    created_at: "2025-11-24T15:28:38.416Z",
    updated_at: "2026-04-17T01:02:04.097Z",
    firebase_uid: "pi7yl1j2gdYayFBcW1SRhzEQbXA3",
    is_hidden_in_community: false,
    home_street: "Zeemansstraat 90",
    home_postcode: "1506 CW",
    home_city: "Zaandam",
    home_country: "Netherlands",
    is_ai_premium: false,
    can_add_spots: false,
    can_create_polls: false,
    can_share_content: false,
  },
  {
    id: 6,
    email: "marth_craandijk@hotmail.com",
    password: null,
    display_name: "Marth ",
    role: "artist",
    bio: null,
    profile_picture: null,
    art_type: "Dancer",
    organization_name: null,
    kvk_number: null,
    btw_number: null,
    kvk_verification_status: "pending",
    kvk_verified_at: null,
    kvk_verification_fail_reason: null,
    is_verified: false,
    is_approved: true,
    location: null,
    stripe_customer_id: null,
    status: "active",
    tos_accepted: false,
    tos_accepted_at: null,
    tos_version: null,
    created_at: "2025-11-26T23:17:40.491Z",
    updated_at: "2025-11-26T23:17:40.491Z",
    firebase_uid: "O69l6ofi1chfG7ri3rLLEPF4eYb2",
    is_hidden_in_community: false,
    home_street: null,
    home_postcode: null,
    home_city: null,
    home_country: null,
    is_ai_premium: false,
    can_add_spots: false,
    can_create_polls: false,
    can_share_content: false,
  },
  {
    id: 7,
    email: "backtothestraat@gmail.com",
    password: null,
    display_name: "Breaker",
    role: "artist",
    bio: null,
    profile_picture: null,
    art_type: "Rapper/MC",
    organization_name: null,
    kvk_number: null,
    btw_number: null,
    kvk_verification_status: "verified",
    kvk_verified_at: "2025-12-01T12:13:49.041Z",
    kvk_verification_fail_reason: null,
    is_verified: false,
    is_approved: true,
    location: null,
    stripe_customer_id: null,
    status: "active",
    tos_accepted: false,
    tos_accepted_at: null,
    tos_version: null,
    created_at: "2025-12-01T12:10:56.805Z",
    updated_at: "2025-12-01T12:13:49.042Z",
    firebase_uid: "aYn8GxnJyjbLrDocMbzkFcmi2Eq1",
    is_hidden_in_community: false,
    home_street: null,
    home_postcode: null,
    home_city: null,
    home_country: null,
    is_ai_premium: false,
    can_add_spots: false,
    can_create_polls: false,
    can_share_content: false,
  },
  {
    id: 8,
    email: "rikim5736@gmail.com",
    password: null,
    display_name: "Urban Demo",
    role: "artist",
    bio: "🎨 Breaking artist & urban culture explorer | Amsterdam 🇳🇱 | Street art, movement, music. Demo account for App Store review — explore all features freely.",
    profile_picture: "https://lh3.googleusercontent.com/a/ACg8ocKP5viA7tRYEVbYzH5BkApSgNrH-sMhrXRTmK49hPMa06EiJg=s96-c",
    art_type: "Breaking / Street Art",
    organization_name: null,
    kvk_number: null,
    btw_number: null,
    kvk_verification_status: "pending",
    kvk_verified_at: null,
    kvk_verification_fail_reason: null,
    is_verified: true,
    is_approved: false,
    location: "Amsterdam, Netherlands",
    stripe_customer_id: null,
    status: "active",
    tos_accepted: false,
    tos_accepted_at: null,
    tos_version: null,
    created_at: "2026-03-18T03:17:30.261Z",
    updated_at: "2026-03-18T03:17:30.261Z",
    firebase_uid: "ZrXUR7timLO3fBQAWmXnYoh1LhH3",
    is_hidden_in_community: false,
    home_street: null,
    home_postcode: null,
    home_city: null,
    home_country: null,
    is_ai_premium: false,
    can_add_spots: false,
    can_create_polls: false,
    can_share_content: false,
  },
  {
    id: 9,
    email: "craandijkmarth@gmail.com",
    password: null,
    display_name: "Marth Craandijk",
    role: "user",
    bio: null,
    profile_picture: "https://lh3.googleusercontent.com/a/ACg8ocJkrtmW9azp1BUpYiw0iT1RU2aK9i-tvLBxcXtqnR0WA7DD5w=s96-c",
    art_type: null,
    organization_name: null,
    kvk_number: null,
    btw_number: null,
    kvk_verification_status: "pending",
    kvk_verified_at: null,
    kvk_verification_fail_reason: null,
    is_verified: false,
    is_approved: true,
    location: null,
    stripe_customer_id: null,
    status: "active",
    tos_accepted: false,
    tos_accepted_at: null,
    tos_version: null,
    created_at: "2026-03-20T11:59:19.006Z",
    updated_at: "2026-03-21T21:27:16.366Z",
    firebase_uid: "K8HcmjrLjsaBNKU8ilqGCMqNyrA3",
    is_hidden_in_community: false,
    home_street: null,
    home_postcode: null,
    home_city: null,
    home_country: null,
    is_ai_premium: false,
    can_add_spots: false,
    can_create_polls: false,
    can_share_content: false,
  },
  {
    id: 10,
    email: "flusqtayufsqp24g38b@icloud.com",
    password: null,
    display_name: "Test",
    role: "enthusiast",
    bio: null,
    profile_picture: null,
    art_type: null,
    organization_name: null,
    kvk_number: null,
    btw_number: null,
    kvk_verification_status: "pending",
    kvk_verified_at: null,
    kvk_verification_fail_reason: null,
    is_verified: false,
    is_approved: true,
    location: null,
    stripe_customer_id: null,
    status: "active",
    tos_accepted: false,
    tos_accepted_at: null,
    tos_version: null,
    created_at: "2026-04-04T08:47:40.030Z",
    updated_at: "2026-04-04T08:47:40.030Z",
    firebase_uid: "LTV1cbwy5qMN6mM1L0e4ozbJNkG2",
    is_hidden_in_community: false,
    home_street: null,
    home_postcode: null,
    home_city: null,
    home_country: null,
    is_ai_premium: false,
    can_add_spots: false,
    can_create_polls: false,
    can_share_content: false,
  },
  {
    id: 11,
    email: "Rash01@hotmail.nl",
    password: null,
    display_name: "Rash",
    role: "enthusiast",
    bio: null,
    profile_picture: null,
    art_type: null,
    organization_name: null,
    kvk_number: null,
    btw_number: null,
    kvk_verification_status: "pending",
    kvk_verified_at: null,
    kvk_verification_fail_reason: null,
    is_verified: false,
    is_approved: true,
    location: null,
    stripe_customer_id: null,
    status: "active",
    tos_accepted: false,
    tos_accepted_at: null,
    tos_version: null,
    created_at: "2026-04-10T15:07:09.777Z",
    updated_at: "2026-04-10T15:07:09.777Z",
    firebase_uid: "4diODIZ6znQVo1HlrtQ9WWsJcE02",
    is_hidden_in_community: false,
    home_street: null,
    home_postcode: null,
    home_city: "Almere",
    home_country: null,
    is_ai_premium: false,
    can_add_spots: false,
    can_create_polls: false,
    can_share_content: false,
  },
  {
    id: 12,
    email: "stichtingcoffeeanddance@gmail.com",
    password: null,
    display_name: "john",
    role: "spot_owner",
    bio: null,
    profile_picture: null,
    art_type: "Gym / Fitness Center",
    organization_name: null,
    kvk_number: null,
    btw_number: null,
    kvk_verification_status: "pending",
    kvk_verified_at: null,
    kvk_verification_fail_reason: null,
    is_verified: false,
    is_approved: false,
    location: null,
    stripe_customer_id: null,
    status: "active",
    tos_accepted: false,
    tos_accepted_at: null,
    tos_version: null,
    created_at: "2026-04-12T03:54:46.522Z",
    updated_at: "2026-04-12T03:54:46.522Z",
    firebase_uid: "28cPNsJ1PTVLK1s3lhNWRKbi1dz2",
    is_hidden_in_community: false,
    home_street: null,
    home_postcode: null,
    home_city: null,
    home_country: null,
    is_ai_premium: false,
    can_add_spots: false,
    can_create_polls: false,
    can_share_content: false,
  },
  {
    id: 13,
    email: "nathalie@ishdancecollective.com",
    password: null,
    display_name: "Nathalie ISH",
    role: "enthusiast",
    bio: null,
    profile_picture: null,
    art_type: null,
    organization_name: null,
    kvk_number: null,
    btw_number: null,
    kvk_verification_status: "pending",
    kvk_verified_at: null,
    kvk_verification_fail_reason: null,
    is_verified: false,
    is_approved: true,
    location: null,
    stripe_customer_id: null,
    status: "active",
    tos_accepted: false,
    tos_accepted_at: null,
    tos_version: null,
    created_at: "2026-04-28T13:23:37.280Z",
    updated_at: "2026-04-28T13:23:37.280Z",
    firebase_uid: "lGJKYDrIPIdCFWx1OGX8tsKayoN2",
    is_hidden_in_community: false,
    home_street: null,
    home_postcode: null,
    home_city: null,
    home_country: null,
    is_ai_premium: false,
    can_add_spots: false,
    can_create_polls: false,
    can_share_content: false,
  },
  {
    id: 14,
    email: "jonathas.8469@gmail.com",
    password: null,
    display_name: "Jhoow",
    role: "enthusiast",
    bio: null,
    profile_picture: null,
    art_type: null,
    organization_name: null,
    kvk_number: null,
    btw_number: null,
    kvk_verification_status: "pending",
    kvk_verified_at: null,
    kvk_verification_fail_reason: null,
    is_verified: false,
    is_approved: true,
    location: null,
    stripe_customer_id: null,
    status: "active",
    tos_accepted: false,
    tos_accepted_at: null,
    tos_version: null,
    created_at: "2026-05-02T22:08:11.960Z",
    updated_at: "2026-05-02T22:08:11.960Z",
    firebase_uid: "tdVB8oNdHSfLwjr7AtNh8tDUhfB3",
    is_hidden_in_community: false,
    home_street: null,
    home_postcode: null,
    home_city: null,
    home_country: null,
    is_ai_premium: false,
    can_add_spots: false,
    can_create_polls: false,
    can_share_content: false,
  },
];

async function run() {
  const client = neon(DATABASE_URL!);
  const db = drizzle(client);

  console.log(`\n🔄  Restoring ${USERS.length} users to production DB…\n`);

  for (const u of USERS) {
    // Build the raw SQL upsert — drizzle's conflict helper works on a single column,
    // so we use sql`` directly to get clean ON CONFLICT … DO UPDATE behaviour.
    await db.execute(sql`
      INSERT INTO users (
        id, email, password, display_name, role, bio, profile_picture,
        art_type, organization_name, kvk_number, btw_number,
        kvk_verification_status, kvk_verified_at, kvk_verification_fail_reason,
        is_verified, is_approved, location, stripe_customer_id,
        status, tos_accepted, tos_accepted_at, tos_version,
        created_at, updated_at, firebase_uid,
        is_hidden_in_community, home_street, home_postcode, home_city, home_country,
        is_ai_premium, can_add_spots, can_create_polls, can_share_content
      ) VALUES (
        ${u.id}, ${u.email}, ${u.password}, ${u.display_name}, ${u.role}, ${u.bio},
        ${u.profile_picture}, ${u.art_type}, ${u.organization_name},
        ${u.kvk_number}, ${u.btw_number}, ${u.kvk_verification_status},
        ${u.kvk_verified_at ? new Date(u.kvk_verified_at) : null},
        ${u.kvk_verification_fail_reason}, ${u.is_verified}, ${u.is_approved},
        ${u.location}, ${u.stripe_customer_id}, ${u.status},
        ${u.tos_accepted}, ${u.tos_accepted_at ? new Date(u.tos_accepted_at) : null},
        ${u.tos_version},
        ${new Date(u.created_at)}, ${new Date(u.updated_at)}, ${u.firebase_uid},
        ${u.is_hidden_in_community}, ${u.home_street}, ${u.home_postcode},
        ${u.home_city}, ${u.home_country}, ${u.is_ai_premium},
        ${u.can_add_spots}, ${u.can_create_polls}, ${u.can_share_content}
      )
      ON CONFLICT (email) DO UPDATE SET
        firebase_uid             = EXCLUDED.firebase_uid,
        display_name             = EXCLUDED.display_name,
        role                     = EXCLUDED.role,
        bio                      = EXCLUDED.bio,
        profile_picture          = EXCLUDED.profile_picture,
        art_type                 = EXCLUDED.art_type,
        organization_name        = EXCLUDED.organization_name,
        kvk_number               = EXCLUDED.kvk_number,
        btw_number               = EXCLUDED.btw_number,
        kvk_verification_status  = EXCLUDED.kvk_verification_status,
        kvk_verified_at          = EXCLUDED.kvk_verified_at,
        is_verified              = EXCLUDED.is_verified,
        is_approved              = EXCLUDED.is_approved,
        location                 = EXCLUDED.location,
        status                   = EXCLUDED.status,
        is_hidden_in_community   = EXCLUDED.is_hidden_in_community,
        home_street              = EXCLUDED.home_street,
        home_postcode            = EXCLUDED.home_postcode,
        home_city                = EXCLUDED.home_city,
        home_country             = EXCLUDED.home_country,
        is_ai_premium            = EXCLUDED.is_ai_premium,
        can_add_spots            = EXCLUDED.can_add_spots,
        can_create_polls         = EXCLUDED.can_create_polls,
        can_share_content        = EXCLUDED.can_share_content,
        updated_at               = now()
    `);
    console.log(`  ✅  ${u.email}  (id=${u.id}, firebase_uid=${u.firebase_uid})`);
  }

  // Reset the serial sequence so the next INSERT gets id = max(id) + 1
  await db.execute(sql`
    SELECT setval(
      pg_get_serial_sequence('users', 'id'),
      (SELECT COALESCE(MAX(id), 1) FROM users),
      true
    )
  `);
  console.log("\n✅  Sequence reset. Migration complete.\n");
}

run().catch(err => {
  console.error("❌  Migration failed:", err);
  process.exit(1);
});
